/**
 * Cook Daemon Protocol
 * The protocol specifies which commands are available from cookd. Cookd is the
 * build server for chef.
 */

import "types"

namespace chef

struct cook_build_request {
    string repository;
    string patch;
    string recipe;
    string part_or_step;
}

service cookd (43) {
    func build(cook_build_request request) : (string id) = 1;
    func status(string id) : (build_status status) = 2;
}
