/**
 * Shared types that are reused through-out the services.
 * Contains some default structures also
 */

namespace chef

enum build_architecture {
    X86 = 0x1,
    X64 = 0x2,
    ARMHF = 0x4,
    ARM64 = 0x8,
    RISCV64 = 0x10
}

enum build_status {
    UNKNOWN,
    QUEUED,
    SOURCING,
    BUILDING,
    PACKING,
    DONE,
    FAILED
}

enum queue_status {
    SUCCESS,
    INTERNAL_ERROR,
    NO_COOK_FOR_ARCHITECTURE
}

enum artifact_type {
    LOG,
    PACKAGE
}
