/**
 * Shared types that are reused through-out the services.
 * Contains some default structures also
 */

namespace chef

enum architecture {
    X86,
    X64,
    ARMHF,
    ARM64,
    RISCV64
}

enum build_status {
    UNKNOWN,
    QUEUED,
    SOURCING,
    BUILDING,
    PACKING,
    DONE,
    FAILED
}

enum queue_status {
    SUCCESS,
    INTERNAL_ERROR,
    NO_COOK_FOR_ARCHITECTURE
}

enum artifact_type {
    LOG,
    PACKAGE
}
