/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#include "chef_cvd_service_client.h"
#include <string.h>
#include <stdlib.h>


GRACHTAPI int gracht_client_get_buffer(gracht_client_t*, gracht_buffer_t*);
GRACHTAPI int gracht_client_get_status_buffer(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);
GRACHTAPI int gracht_client_status_finalize(gracht_client_t*, struct gracht_buffer*);
GRACHTAPI int gracht_client_invoke(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);

int chef_cvd_subscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 43);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_cvd_unsubscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 43);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_cvd_create(gracht_client_t* client, struct gracht_message_context* context, const struct chef_create_parameters* params) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_chef_create_parameters(&__buffer, params);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_cvd_create_result(gracht_client_t* client, struct gracht_message_context* context, char* id_out, const uint32_t id_max_length, enum chef_status* st_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    deserialize_string_copy(&__buffer, &id_out[0], id_max_length);
    *st_out = (enum chef_status)deserialize_int(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_cvd_spawn(gracht_client_t* client, struct gracht_message_context* context, const struct chef_spawn_parameters* params) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 2);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_chef_spawn_parameters(&__buffer, params);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_cvd_spawn_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* pid_out, enum chef_status* st_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *pid_out = deserialize_uint(&__buffer);
    *st_out = (enum chef_status)deserialize_int(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_cvd_kill(gracht_client_t* client, struct gracht_message_context* context, const char* container_id, const unsigned int pid) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 3);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, container_id);
    serialize_uint(&__buffer, pid);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_cvd_kill_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_status* st_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *st_out = (enum chef_status)deserialize_int(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_cvd_upload(gracht_client_t* client, struct gracht_message_context* context, const struct chef_file_parameters* params) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 4);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_chef_file_parameters(&__buffer, params);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_cvd_upload_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_status* st_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *st_out = (enum chef_status)deserialize_int(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_cvd_download(gracht_client_t* client, struct gracht_message_context* context, const struct chef_file_parameters* params) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 5);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_chef_file_parameters(&__buffer, params);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_cvd_download_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_status* st_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *st_out = (enum chef_status)deserialize_int(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_cvd_destroy(gracht_client_t* client, struct gracht_message_context* context, const char* container_id) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 6);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, container_id);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_cvd_destroy_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_status* st_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *st_out = (enum chef_status)deserialize_int(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

