/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_WAITERD_COOK_SERVICE_H__
#define __CHEF_WAITERD_COOK_SERVICE_H__

#include <assert.h>
#include <gracht/types.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>


#define SERVICE_CHEF_WAITERD_COOK_ID 45
#define SERVICE_CHEF_WAITERD_COOK_FUNCTION_COUNT 4

#define SERVICE_CHEF_WAITERD_COOK_READY_ID 1
#define SERVICE_CHEF_WAITERD_COOK_UPDATE_ID 2
#define SERVICE_CHEF_WAITERD_COOK_STATUS_ID 3
#define SERVICE_CHEF_WAITERD_COOK_ARTIFACT_ID 4

#define SERVICE_CHEF_WAITERD_COOK_EVENT_UPDATE_REQUEST_ID 5
#define SERVICE_CHEF_WAITERD_COOK_EVENT_BUILD_REQUEST_ID 6


#ifndef GRMIN
#define GRMIN(a, b) (((a)<(b))?(a):(b))
#endif //! GRMIN

#ifndef __GRACHT_SERVICE_SHARED_SERIALIZERS
#define __GRACHT_SERVICE_SHARED_SERIALIZERS
#define SERIALIZE_VALUE(name, type) static inline void serialize_##name(gracht_buffer_t* buffer, type value) { \
                                        *((type*)&buffer->data[buffer->index]) = value; buffer->index += sizeof(type); \
                                    }

#define DESERIALIZE_VALUE(name, type) static inline type deserialize_##name(gracht_buffer_t* buffer) { \
                                          type value = *((type*)&buffer->data[buffer->index]); \
                                          buffer->index += sizeof(type); \
                                          return value; \
                                       }


SERIALIZE_VALUE(uint8, uint8_t)
DESERIALIZE_VALUE(uint8, uint8_t)
SERIALIZE_VALUE(int8, int8_t)
DESERIALIZE_VALUE(int8, int8_t)
SERIALIZE_VALUE(uint16, uint16_t)
DESERIALIZE_VALUE(uint16, uint16_t)
SERIALIZE_VALUE(int16, int16_t)
DESERIALIZE_VALUE(int16, int16_t)
SERIALIZE_VALUE(uint32, uint32_t)
DESERIALIZE_VALUE(uint32, uint32_t)
SERIALIZE_VALUE(int32, int32_t)
DESERIALIZE_VALUE(int32, int32_t)
SERIALIZE_VALUE(uint64, uint64_t)
DESERIALIZE_VALUE(uint64, uint64_t)
SERIALIZE_VALUE(int64, int64_t)
DESERIALIZE_VALUE(int64, int64_t)
SERIALIZE_VALUE(long, long)
DESERIALIZE_VALUE(long, long)
SERIALIZE_VALUE(ulong, size_t)
DESERIALIZE_VALUE(ulong, size_t)
SERIALIZE_VALUE(uint, unsigned int)
DESERIALIZE_VALUE(uint, unsigned int)
SERIALIZE_VALUE(int, int)
DESERIALIZE_VALUE(int, int)
SERIALIZE_VALUE(bool, uint8_t)
DESERIALIZE_VALUE(bool, uint8_t)
SERIALIZE_VALUE(float, float)
DESERIALIZE_VALUE(float, float)
SERIALIZE_VALUE(double, double)
DESERIALIZE_VALUE(double, double)

static inline void serialize_string(gracht_buffer_t* buffer, const char* string) {
    uint32_t length = string != NULL ? (uint32_t)strlen(string) : 0;
    *((uint32_t*)&buffer->data[buffer->index]) = length;
    if (length == 0) {
        buffer->data[buffer->index + sizeof(uint32_t)] = 0;
        buffer->index += sizeof(uint32_t) + 1;
        return;
    }
    memcpy(&buffer->data[buffer->index + sizeof(uint32_t)], string, length);
    buffer->data[buffer->index + sizeof(uint32_t) + length] = 0;
    buffer->index += (sizeof(uint32_t) + length + 1);
}

static inline void deserialize_string_copy(gracht_buffer_t* buffer, char* out, uint32_t maxLength) {
    uint32_t length = *((uint32_t*)&buffer->data[buffer->index]);
    uint32_t clampedLength = GRMIN(length, maxLength - 1);
    if (clampedLength > 0) {
        memcpy(out, &buffer->data[buffer->index + sizeof(uint32_t)], clampedLength);
    }
    out[clampedLength] = 0;
    buffer->index += sizeof(uint32_t) + length + 1;
}

static inline char* deserialize_string_nocopy(gracht_buffer_t* buffer) {
    uint32_t length = *((uint32_t*)&buffer->data[buffer->index]);
    char*    string = &buffer->data[buffer->index + sizeof(uint32_t)];
    buffer->index += sizeof(uint32_t) + length + 1;
    return string;
}
#endif //! __GRACHT_SERVICE_SHARED_SERIALIZERS


struct chef_waiter_build_request;
static void serialize_chef_waiter_build_request(gracht_buffer_t* buffer, const struct chef_waiter_build_request* in);
static void deserialize_chef_waiter_build_request(gracht_buffer_t* buffer, struct chef_waiter_build_request* out);

struct chef_waiter_status_response;
static void serialize_chef_waiter_status_response(gracht_buffer_t* buffer, const struct chef_waiter_status_response* in);
static void deserialize_chef_waiter_status_response(gracht_buffer_t* buffer, struct chef_waiter_status_response* out);

struct chef_waiter_agent_info;
static void serialize_chef_waiter_agent_info(gracht_buffer_t* buffer, const struct chef_waiter_agent_info* in);
static void deserialize_chef_waiter_agent_info(gracht_buffer_t* buffer, struct chef_waiter_agent_info* out);

struct chef_cook_ready_event;
static void serialize_chef_cook_ready_event(gracht_buffer_t* buffer, const struct chef_cook_ready_event* in);
static void deserialize_chef_cook_ready_event(gracht_buffer_t* buffer, struct chef_cook_ready_event* out);

struct chef_cook_update_event;
static void serialize_chef_cook_update_event(gracht_buffer_t* buffer, const struct chef_cook_update_event* in);
static void deserialize_chef_cook_update_event(gracht_buffer_t* buffer, struct chef_cook_update_event* out);

struct chef_cook_build_event;
static void serialize_chef_cook_build_event(gracht_buffer_t* buffer, const struct chef_cook_build_event* in);
static void deserialize_chef_cook_build_event(gracht_buffer_t* buffer, struct chef_cook_build_event* out);

struct chef_cook_artifact_event;
static void serialize_chef_cook_artifact_event(gracht_buffer_t* buffer, const struct chef_cook_artifact_event* in);
static void deserialize_chef_cook_artifact_event(gracht_buffer_t* buffer, struct chef_cook_artifact_event* out);

struct chef_cook_update_request;
static void serialize_chef_cook_update_request(gracht_buffer_t* buffer, const struct chef_cook_update_request* in);
static void deserialize_chef_cook_update_request(gracht_buffer_t* buffer, struct chef_cook_update_request* out);


#ifndef __CHEF_BUILD_ARCHITECTURE_DEFINED__
#define __CHEF_BUILD_ARCHITECTURE_DEFINED__
enum chef_build_architecture {
    CHEF_BUILD_ARCHITECTURE_X86 = 1,
    CHEF_BUILD_ARCHITECTURE_X64 = 2,
    CHEF_BUILD_ARCHITECTURE_ARMHF = 4,
    CHEF_BUILD_ARCHITECTURE_ARM64 = 8,
    CHEF_BUILD_ARCHITECTURE_RISCV64 = 16,
};
#endif //! __CHEF_BUILD_ARCHITECTURE_DEFINED__

#ifndef __CHEF_BUILD_STATUS_DEFINED__
#define __CHEF_BUILD_STATUS_DEFINED__
enum chef_build_status {
    CHEF_BUILD_STATUS_UNKNOWN,
    CHEF_BUILD_STATUS_QUEUED,
    CHEF_BUILD_STATUS_SOURCING,
    CHEF_BUILD_STATUS_BUILDING,
    CHEF_BUILD_STATUS_PACKING,
    CHEF_BUILD_STATUS_DONE,
    CHEF_BUILD_STATUS_FAILED,
};
#endif //! __CHEF_BUILD_STATUS_DEFINED__

#ifndef __CHEF_QUEUE_STATUS_DEFINED__
#define __CHEF_QUEUE_STATUS_DEFINED__
enum chef_queue_status {
    CHEF_QUEUE_STATUS_SUCCESS,
    CHEF_QUEUE_STATUS_INTERNAL_ERROR,
    CHEF_QUEUE_STATUS_NO_COOK_FOR_ARCHITECTURE,
};
#endif //! __CHEF_QUEUE_STATUS_DEFINED__

#ifndef __CHEF_ARTIFACT_TYPE_DEFINED__
#define __CHEF_ARTIFACT_TYPE_DEFINED__
enum chef_artifact_type {
    CHEF_ARTIFACT_TYPE_LOG,
    CHEF_ARTIFACT_TYPE_PACKAGE,
};
#endif //! __CHEF_ARTIFACT_TYPE_DEFINED__


#ifndef __CHEF_WAITER_BUILD_REQUEST_DEFINED__
#define __CHEF_WAITER_BUILD_REQUEST_DEFINED__
struct chef_waiter_build_request {
    enum chef_build_architecture arch;
    char* platform;
    char* url;
    char* patch;
    char* recipe;
};


static void chef_waiter_build_request_init(struct chef_waiter_build_request* in) {
    memset(in, 0, sizeof(struct chef_waiter_build_request));
}

static void chef_waiter_build_request_copy(const struct chef_waiter_build_request* in, struct chef_waiter_build_request* out) {
    out->arch = in->arch;
    if (in->platform != NULL) {
        out->platform = strdup(in->platform);
    } else {
        out->platform = NULL;
    }
    if (in->url != NULL) {
        out->url = strdup(in->url);
    } else {
        out->url = NULL;
    }
    if (in->patch != NULL) {
        out->patch = strdup(in->patch);
    } else {
        out->patch = NULL;
    }
    if (in->recipe != NULL) {
        out->recipe = strdup(in->recipe);
    } else {
        out->recipe = NULL;
    }
}

static void chef_waiter_build_request_destroy(struct chef_waiter_build_request* in) {
    if (in->platform) {
        free(in->platform);
    }
    if (in->url) {
        free(in->url);
    }
    if (in->patch) {
        free(in->patch);
    }
    if (in->recipe) {
        free(in->recipe);
    }
}

#endif //! __CHEF_WAITER_BUILD_REQUEST_DEFINED__

#ifndef __CHEF_WAITER_STATUS_RESPONSE_DEFINED__
#define __CHEF_WAITER_STATUS_RESPONSE_DEFINED__
struct chef_waiter_status_response {
    enum chef_build_architecture arch;
    enum chef_build_status status;
};


static void chef_waiter_status_response_init(struct chef_waiter_status_response* in) {
    memset(in, 0, sizeof(struct chef_waiter_status_response));
}

static void chef_waiter_status_response_copy(const struct chef_waiter_status_response* in, struct chef_waiter_status_response* out) {
    out->arch = in->arch;
    out->status = in->status;
}

static void chef_waiter_status_response_destroy(struct chef_waiter_status_response* in) {
    (void)in;
}

#endif //! __CHEF_WAITER_STATUS_RESPONSE_DEFINED__

#ifndef __CHEF_WAITER_AGENT_INFO_DEFINED__
#define __CHEF_WAITER_AGENT_INFO_DEFINED__
struct chef_waiter_agent_info {
    char* name;
    int online;
    enum chef_build_architecture architectures;
    int queue_size;
};


static void chef_waiter_agent_info_init(struct chef_waiter_agent_info* in) {
    memset(in, 0, sizeof(struct chef_waiter_agent_info));
}

static void chef_waiter_agent_info_copy(const struct chef_waiter_agent_info* in, struct chef_waiter_agent_info* out) {
    if (in->name != NULL) {
        out->name = strdup(in->name);
    } else {
        out->name = NULL;
    }
    out->online = in->online;
    out->architectures = in->architectures;
    out->queue_size = in->queue_size;
}

static void chef_waiter_agent_info_destroy(struct chef_waiter_agent_info* in) {
    if (in->name) {
        free(in->name);
    }
}

#endif //! __CHEF_WAITER_AGENT_INFO_DEFINED__

#ifndef __CHEF_COOK_READY_EVENT_DEFINED__
#define __CHEF_COOK_READY_EVENT_DEFINED__
struct chef_cook_ready_event {
    enum chef_build_architecture archs;
};


static void chef_cook_ready_event_init(struct chef_cook_ready_event* in) {
    memset(in, 0, sizeof(struct chef_cook_ready_event));
}

static void chef_cook_ready_event_copy(const struct chef_cook_ready_event* in, struct chef_cook_ready_event* out) {
    out->archs = in->archs;
}

static void chef_cook_ready_event_destroy(struct chef_cook_ready_event* in) {
    (void)in;
}

#endif //! __CHEF_COOK_READY_EVENT_DEFINED__

#ifndef __CHEF_COOK_UPDATE_EVENT_DEFINED__
#define __CHEF_COOK_UPDATE_EVENT_DEFINED__
struct chef_cook_update_event {
    int queue_size;
};


static void chef_cook_update_event_init(struct chef_cook_update_event* in) {
    memset(in, 0, sizeof(struct chef_cook_update_event));
}

static void chef_cook_update_event_copy(const struct chef_cook_update_event* in, struct chef_cook_update_event* out) {
    out->queue_size = in->queue_size;
}

static void chef_cook_update_event_destroy(struct chef_cook_update_event* in) {
    (void)in;
}

#endif //! __CHEF_COOK_UPDATE_EVENT_DEFINED__

#ifndef __CHEF_COOK_BUILD_EVENT_DEFINED__
#define __CHEF_COOK_BUILD_EVENT_DEFINED__
struct chef_cook_build_event {
    char* id;
    enum chef_build_status status;
};


static void chef_cook_build_event_init(struct chef_cook_build_event* in) {
    memset(in, 0, sizeof(struct chef_cook_build_event));
}

static void chef_cook_build_event_copy(const struct chef_cook_build_event* in, struct chef_cook_build_event* out) {
    if (in->id != NULL) {
        out->id = strdup(in->id);
    } else {
        out->id = NULL;
    }
    out->status = in->status;
}

static void chef_cook_build_event_destroy(struct chef_cook_build_event* in) {
    if (in->id) {
        free(in->id);
    }
}

#endif //! __CHEF_COOK_BUILD_EVENT_DEFINED__

#ifndef __CHEF_COOK_ARTIFACT_EVENT_DEFINED__
#define __CHEF_COOK_ARTIFACT_EVENT_DEFINED__
struct chef_cook_artifact_event {
    char* id;
    enum chef_artifact_type type;
    char* uri;
};


static void chef_cook_artifact_event_init(struct chef_cook_artifact_event* in) {
    memset(in, 0, sizeof(struct chef_cook_artifact_event));
}

static void chef_cook_artifact_event_copy(const struct chef_cook_artifact_event* in, struct chef_cook_artifact_event* out) {
    if (in->id != NULL) {
        out->id = strdup(in->id);
    } else {
        out->id = NULL;
    }
    out->type = in->type;
    if (in->uri != NULL) {
        out->uri = strdup(in->uri);
    } else {
        out->uri = NULL;
    }
}

static void chef_cook_artifact_event_destroy(struct chef_cook_artifact_event* in) {
    if (in->id) {
        free(in->id);
    }
    if (in->uri) {
        free(in->uri);
    }
}

#endif //! __CHEF_COOK_ARTIFACT_EVENT_DEFINED__

#ifndef __CHEF_COOK_UPDATE_REQUEST_DEFINED__
#define __CHEF_COOK_UPDATE_REQUEST_DEFINED__
struct chef_cook_update_request {
    int unused;
};


static void chef_cook_update_request_init(struct chef_cook_update_request* in) {
    memset(in, 0, sizeof(struct chef_cook_update_request));
}

static void chef_cook_update_request_copy(const struct chef_cook_update_request* in, struct chef_cook_update_request* out) {
    out->unused = in->unused;
}

static void chef_cook_update_request_destroy(struct chef_cook_update_request* in) {
    (void)in;
}

#endif //! __CHEF_COOK_UPDATE_REQUEST_DEFINED__

#ifndef __GRACHT_CHEF_WAITER_BUILD_REQUEST_SERIALIZER_DEFINED__
#define __GRACHT_CHEF_WAITER_BUILD_REQUEST_SERIALIZER_DEFINED__
static void serialize_chef_waiter_build_request(gracht_buffer_t* buffer, const struct chef_waiter_build_request* in) {
    serialize_int(buffer, (int)(in->arch));
    serialize_string(buffer, in->platform);
    serialize_string(buffer, in->url);
    serialize_string(buffer, in->patch);
    serialize_string(buffer, in->recipe);
}

static void deserialize_chef_waiter_build_request(gracht_buffer_t* buffer, struct chef_waiter_build_request* out) {
    out->arch = (enum chef_build_architecture)deserialize_int(buffer);
    uint32_t _platform_length = *((uint32_t*)&buffer->data[buffer->index]);
    out->platform = malloc(_platform_length + 1);
    assert(out->platform != NULL);
    deserialize_string_copy(buffer, &out->platform[0], 0);
    uint32_t _url_length = *((uint32_t*)&buffer->data[buffer->index]);
    out->url = malloc(_url_length + 1);
    assert(out->url != NULL);
    deserialize_string_copy(buffer, &out->url[0], 0);
    uint32_t _patch_length = *((uint32_t*)&buffer->data[buffer->index]);
    out->patch = malloc(_patch_length + 1);
    assert(out->patch != NULL);
    deserialize_string_copy(buffer, &out->patch[0], 0);
    uint32_t _recipe_length = *((uint32_t*)&buffer->data[buffer->index]);
    out->recipe = malloc(_recipe_length + 1);
    assert(out->recipe != NULL);
    deserialize_string_copy(buffer, &out->recipe[0], 0);
}
#endif //! __GRACHT_CHEF_WAITER_BUILD_REQUEST_SERIALIZER_DEFINED__

#ifndef __GRACHT_CHEF_WAITER_STATUS_RESPONSE_SERIALIZER_DEFINED__
#define __GRACHT_CHEF_WAITER_STATUS_RESPONSE_SERIALIZER_DEFINED__
static void serialize_chef_waiter_status_response(gracht_buffer_t* buffer, const struct chef_waiter_status_response* in) {
    serialize_int(buffer, (int)(in->arch));
    serialize_int(buffer, (int)(in->status));
}

static void deserialize_chef_waiter_status_response(gracht_buffer_t* buffer, struct chef_waiter_status_response* out) {
    out->arch = (enum chef_build_architecture)deserialize_int(buffer);
    out->status = (enum chef_build_status)deserialize_int(buffer);
}
#endif //! __GRACHT_CHEF_WAITER_STATUS_RESPONSE_SERIALIZER_DEFINED__

#ifndef __GRACHT_CHEF_WAITER_AGENT_INFO_SERIALIZER_DEFINED__
#define __GRACHT_CHEF_WAITER_AGENT_INFO_SERIALIZER_DEFINED__
static void serialize_chef_waiter_agent_info(gracht_buffer_t* buffer, const struct chef_waiter_agent_info* in) {
    serialize_string(buffer, in->name);
    serialize_int(buffer, in->online);
    serialize_int(buffer, (int)(in->architectures));
    serialize_int(buffer, in->queue_size);
}

static void deserialize_chef_waiter_agent_info(gracht_buffer_t* buffer, struct chef_waiter_agent_info* out) {
    uint32_t _name_length = *((uint32_t*)&buffer->data[buffer->index]);
    out->name = malloc(_name_length + 1);
    assert(out->name != NULL);
    deserialize_string_copy(buffer, &out->name[0], 0);
    out->online = deserialize_int(buffer);
    out->architectures = (enum chef_build_architecture)deserialize_int(buffer);
    out->queue_size = deserialize_int(buffer);
}
#endif //! __GRACHT_CHEF_WAITER_AGENT_INFO_SERIALIZER_DEFINED__

#ifndef __GRACHT_CHEF_COOK_READY_EVENT_SERIALIZER_DEFINED__
#define __GRACHT_CHEF_COOK_READY_EVENT_SERIALIZER_DEFINED__
static void serialize_chef_cook_ready_event(gracht_buffer_t* buffer, const struct chef_cook_ready_event* in) {
    serialize_int(buffer, (int)(in->archs));
}

static void deserialize_chef_cook_ready_event(gracht_buffer_t* buffer, struct chef_cook_ready_event* out) {
    out->archs = (enum chef_build_architecture)deserialize_int(buffer);
}
#endif //! __GRACHT_CHEF_COOK_READY_EVENT_SERIALIZER_DEFINED__

#ifndef __GRACHT_CHEF_COOK_UPDATE_EVENT_SERIALIZER_DEFINED__
#define __GRACHT_CHEF_COOK_UPDATE_EVENT_SERIALIZER_DEFINED__
static void serialize_chef_cook_update_event(gracht_buffer_t* buffer, const struct chef_cook_update_event* in) {
    serialize_int(buffer, in->queue_size);
}

static void deserialize_chef_cook_update_event(gracht_buffer_t* buffer, struct chef_cook_update_event* out) {
    out->queue_size = deserialize_int(buffer);
}
#endif //! __GRACHT_CHEF_COOK_UPDATE_EVENT_SERIALIZER_DEFINED__

#ifndef __GRACHT_CHEF_COOK_BUILD_EVENT_SERIALIZER_DEFINED__
#define __GRACHT_CHEF_COOK_BUILD_EVENT_SERIALIZER_DEFINED__
static void serialize_chef_cook_build_event(gracht_buffer_t* buffer, const struct chef_cook_build_event* in) {
    serialize_string(buffer, in->id);
    serialize_int(buffer, (int)(in->status));
}

static void deserialize_chef_cook_build_event(gracht_buffer_t* buffer, struct chef_cook_build_event* out) {
    uint32_t _id_length = *((uint32_t*)&buffer->data[buffer->index]);
    out->id = malloc(_id_length + 1);
    assert(out->id != NULL);
    deserialize_string_copy(buffer, &out->id[0], 0);
    out->status = (enum chef_build_status)deserialize_int(buffer);
}
#endif //! __GRACHT_CHEF_COOK_BUILD_EVENT_SERIALIZER_DEFINED__

#ifndef __GRACHT_CHEF_COOK_ARTIFACT_EVENT_SERIALIZER_DEFINED__
#define __GRACHT_CHEF_COOK_ARTIFACT_EVENT_SERIALIZER_DEFINED__
static void serialize_chef_cook_artifact_event(gracht_buffer_t* buffer, const struct chef_cook_artifact_event* in) {
    serialize_string(buffer, in->id);
    serialize_int(buffer, (int)(in->type));
    serialize_string(buffer, in->uri);
}

static void deserialize_chef_cook_artifact_event(gracht_buffer_t* buffer, struct chef_cook_artifact_event* out) {
    uint32_t _id_length = *((uint32_t*)&buffer->data[buffer->index]);
    out->id = malloc(_id_length + 1);
    assert(out->id != NULL);
    deserialize_string_copy(buffer, &out->id[0], 0);
    out->type = (enum chef_artifact_type)deserialize_int(buffer);
    uint32_t _uri_length = *((uint32_t*)&buffer->data[buffer->index]);
    out->uri = malloc(_uri_length + 1);
    assert(out->uri != NULL);
    deserialize_string_copy(buffer, &out->uri[0], 0);
}
#endif //! __GRACHT_CHEF_COOK_ARTIFACT_EVENT_SERIALIZER_DEFINED__

#ifndef __GRACHT_CHEF_COOK_UPDATE_REQUEST_SERIALIZER_DEFINED__
#define __GRACHT_CHEF_COOK_UPDATE_REQUEST_SERIALIZER_DEFINED__
static void serialize_chef_cook_update_request(gracht_buffer_t* buffer, const struct chef_cook_update_request* in) {
    serialize_int(buffer, in->unused);
}

static void deserialize_chef_cook_update_request(gracht_buffer_t* buffer, struct chef_cook_update_request* out) {
    out->unused = deserialize_int(buffer);
}
#endif //! __GRACHT_CHEF_COOK_UPDATE_REQUEST_SERIALIZER_DEFINED__

#endif //! __CHEF_WAITERD_COOK_SERVICE_H__
