/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#include "chef_waiterd_service_client.h"
#include <string.h>
#include <stdlib.h>


GRACHTAPI int gracht_client_get_buffer(gracht_client_t*, gracht_buffer_t*);
GRACHTAPI int gracht_client_get_status_buffer(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);
GRACHTAPI int gracht_client_status_finalize(gracht_client_t*, struct gracht_buffer*);
GRACHTAPI int gracht_client_invoke(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);

int chef_waiterd_subscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 44);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_unsubscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 44);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_build(gracht_client_t* client, struct gracht_message_context* context, const struct chef_waiter_build_request* request) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_chef_waiter_build_request(&__buffer, request);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_build_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_queue_status* status_out, char* id_out, const uint32_t id_max_length) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *status_out = (enum chef_queue_status)deserialize_int(&__buffer);
    deserialize_string_copy(&__buffer, &id_out[0], id_max_length);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_waiterd_status(gracht_client_t* client, struct gracht_message_context* context, const char* id) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 2);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, id);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_status_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_waiter_status_response* response_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    deserialize_chef_waiter_status_response(&__buffer, response_out);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_waiterd_artifact(gracht_client_t* client, struct gracht_message_context* context, const char* id, const enum chef_artifact_type type) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 3);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, id);
    serialize_int(&__buffer, (int)type);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_artifact_result(gracht_client_t* client, struct gracht_message_context* context, char* link_out, const uint32_t link_max_length) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    deserialize_string_copy(&__buffer, &link_out[0], link_max_length);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_waiterd_list_agents(gracht_client_t* client, struct gracht_message_context* context, const enum chef_build_architecture arch_filter) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 4);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_int(&__buffer, (int)arch_filter);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_list_agents_result(gracht_client_t* client, struct gracht_message_context* context, int* count_out, struct chef_waiter_agent_info* agents_out, const uint32_t agents_count) {
    gracht_buffer_t __buffer;
    int __status;
    uint32_t __count;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *count_out = deserialize_int(&__buffer);
    __count = deserialize_uint32(&__buffer);
    for (uint32_t __i = 0; __i < GRMIN(__count, agents_count); __i++) {
        deserialize_chef_waiter_agent_info(&__buffer, &agents_out[__i]);
    }
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_waiterd_agent_info(gracht_client_t* client, struct gracht_message_context* context, const char* name) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 5);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, name);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_agent_info_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_waiter_agent_info* info_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    deserialize_chef_waiter_agent_info(&__buffer, info_out);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

