/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_WAITERD_SERVICE_SERVER_H__
#define __CHEF_WAITERD_SERVICE_SERVER_H__

#include <gracht/server.h>

#include "chef_waiterd_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    /**
     * Invocation callback prototypes that must be defined. These are the functions
     * that will be called when a message is received.
     */
    void chef_waiterd_build_invocation(struct gracht_message* message, const struct chef_waiter_build_request* request);
    void chef_waiterd_status_invocation(struct gracht_message* message, const char* id);
    void chef_waiterd_artifact_invocation(struct gracht_message* message, const char* id, const enum chef_artifact_type type);
    void chef_waiterd_list_agents_invocation(struct gracht_message* message, const enum chef_build_architecture arch_filter);
    void chef_waiterd_agent_info_invocation(struct gracht_message* message, const char* name);

    /**
     * Response functions that can be invoked from invocations. These will format a response
     * message based on a message context.
     */
    int chef_waiterd_build_response(struct gracht_message* message, enum chef_queue_status status, char* id);
    int chef_waiterd_status_response(struct gracht_message* message, struct chef_waiter_status_response* response);
    int chef_waiterd_artifact_response(struct gracht_message* message, char* link);
    int chef_waiterd_list_agents_response(struct gracht_message* message, int count, struct chef_waiter_agent_info* agents, uint32_t agents_count);
    int chef_waiterd_agent_info_response(struct gracht_message* message, struct chef_waiter_agent_info* info);

    extern gracht_protocol_t chef_waiterd_server_protocol;

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_WAITERD_SERVICE_SERVER_H__
