/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_WAITERD_COOK_SERVICE_SERVER_H__
#define __CHEF_WAITERD_COOK_SERVICE_SERVER_H__

#include <gracht/server.h>

#include "chef_waiterd_cook_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    /**
     * Invocation callback prototypes that must be defined. These are the functions
     * that will be called when a message is received.
     */
    void chef_waiterd_cook_ready_invocation(struct gracht_message* message, const struct chef_cook_ready_event* evt);
    void chef_waiterd_cook_update_invocation(struct gracht_message* message, const struct chef_cook_update_event* evt);
    void chef_waiterd_cook_status_invocation(struct gracht_message* message, const struct chef_cook_build_event* evt);
    void chef_waiterd_cook_artifact_invocation(struct gracht_message* message, const struct chef_cook_artifact_event* evt);

    /**
     * Response functions that can be invoked from invocations. These will format a response
     * message based on a message context.
     */

    /**
     * Event functions that can be invoked at any point in time.
     */
    int chef_waiterd_cook_event_update_request_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_cook_update_request* request);
    int chef_waiterd_cook_event_update_request_all(gracht_server_t* server, const struct chef_cook_update_request* request);
    int chef_waiterd_cook_event_build_request_single(gracht_server_t* server, const gracht_conn_t client, const char* id, const struct chef_waiter_build_request* request);
    int chef_waiterd_cook_event_build_request_all(gracht_server_t* server, const char* id, const struct chef_waiter_build_request* request);

    extern gracht_protocol_t chef_waiterd_cook_server_protocol;

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_WAITERD_COOK_SERVICE_SERVER_H__
