/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_SERVED_SERVICE_SERVER_H__
#define __CHEF_SERVED_SERVICE_SERVER_H__

#include <gracht/server.h>

#include "chef_served_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    /**
     * Invocation callback prototypes that must be defined. These are the functions
     * that will be called when a message is received.
     */
    void chef_served_install_invocation(struct gracht_message* message, const char* publisher, const char* path);
    void chef_served_remove_invocation(struct gracht_message* message, const char* packageName);
    void chef_served_info_invocation(struct gracht_message* message, const char* packageName);
    void chef_served_listcount_invocation(struct gracht_message* message);
    void chef_served_list_invocation(struct gracht_message* message);
    void chef_served_get_command_invocation(struct gracht_message* message, const char* mountPath);

    /**
     * Response functions that can be invoked from invocations. These will format a response
     * message based on a message context.
     */
    int chef_served_remove_response(struct gracht_message* message, int result);
    int chef_served_info_response(struct gracht_message* message, struct chef_served_package* info);
    int chef_served_listcount_response(struct gracht_message* message, unsigned int count);
    int chef_served_list_response(struct gracht_message* message, struct chef_served_package* packages, uint32_t packages_count);
    int chef_served_get_command_response(struct gracht_message* message, struct chef_served_command* command);

    /**
     * Event functions that can be invoked at any point in time.
     */
    int chef_served_event_package_installed_single(gracht_server_t* server, const gracht_conn_t client, const enum chef_install_status status, const struct chef_served_package* info);
    int chef_served_event_package_installed_all(gracht_server_t* server, const enum chef_install_status status, const struct chef_served_package* info);
    int chef_served_event_package_removed_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_served_package* info);
    int chef_served_event_package_removed_all(gracht_server_t* server, const struct chef_served_package* info);
    int chef_served_event_package_updated_single(gracht_server_t* server, const gracht_conn_t client, const enum chef_update_status status, const struct chef_served_package* info);
    int chef_served_event_package_updated_all(gracht_server_t* server, const enum chef_update_status status, const struct chef_served_package* info);

    extern gracht_protocol_t chef_served_server_protocol;

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_SERVED_SERVICE_SERVER_H__
