/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_CVD_SERVICE_SERVER_H__
#define __CHEF_CVD_SERVICE_SERVER_H__

#include <gracht/server.h>

#include "chef_cvd_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    /**
     * Invocation callback prototypes that must be defined. These are the functions
     * that will be called when a message is received.
     */
    void chef_cvd_create_invocation(struct gracht_message* message, const struct chef_create_parameters* params);
    void chef_cvd_spawn_invocation(struct gracht_message* message, const struct chef_spawn_parameters* params);
    void chef_cvd_kill_invocation(struct gracht_message* message, const char* container_id, const unsigned int pid);
    void chef_cvd_upload_invocation(struct gracht_message* message, const struct chef_file_parameters* params);
    void chef_cvd_download_invocation(struct gracht_message* message, const struct chef_file_parameters* params);
    void chef_cvd_destroy_invocation(struct gracht_message* message, const char* container_id);

    /**
     * Response functions that can be invoked from invocations. These will format a response
     * message based on a message context.
     */
    int chef_cvd_create_response(struct gracht_message* message, char* id, enum chef_status st);
    int chef_cvd_spawn_response(struct gracht_message* message, unsigned int pid, enum chef_status st);
    int chef_cvd_kill_response(struct gracht_message* message, enum chef_status st);
    int chef_cvd_upload_response(struct gracht_message* message, enum chef_status st);
    int chef_cvd_download_response(struct gracht_message* message, enum chef_status st);
    int chef_cvd_destroy_response(struct gracht_message* message, enum chef_status st);

    extern gracht_protocol_t chef_cvd_server_protocol;

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_CVD_SERVICE_SERVER_H__
