/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#include "chef_waiterd_cook_service_server.h"
#include <string.h>
#include <stdlib.h>


GRACHTAPI int gracht_server_get_buffer(gracht_server_t*, gracht_buffer_t*);
GRACHTAPI int gracht_server_respond(struct gracht_message*, gracht_buffer_t*);
GRACHTAPI int gracht_server_send_event(gracht_server_t*, gracht_conn_t client, gracht_buffer_t*, unsigned int flags);
GRACHTAPI int gracht_server_broadcast_event(gracht_server_t*, gracht_buffer_t*, unsigned int flags);

void __chef_waiterd_cook_ready_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_waiterd_cook_update_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_waiterd_cook_status_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_waiterd_cook_artifact_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);

static gracht_protocol_function_t chef_waiterd_cook_callbacks[4] = {
    { SERVICE_CHEF_WAITERD_COOK_READY_ID, __chef_waiterd_cook_ready_internal },
    { SERVICE_CHEF_WAITERD_COOK_UPDATE_ID, __chef_waiterd_cook_update_internal },
    { SERVICE_CHEF_WAITERD_COOK_STATUS_ID, __chef_waiterd_cook_status_internal },
    { SERVICE_CHEF_WAITERD_COOK_ARTIFACT_ID, __chef_waiterd_cook_artifact_internal },
};

gracht_protocol_t chef_waiterd_cook_server_protocol = GRACHT_PROTOCOL_INIT(45, "chef_waiterd_cook", 4, chef_waiterd_cook_callbacks);

void __chef_waiterd_cook_ready_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_cook_ready_event evt;
    deserialize_chef_cook_ready_event(__buffer, &evt);
    chef_waiterd_cook_ready_invocation(__message, &evt);
    chef_cook_ready_event_destroy(&evt);
}

void __chef_waiterd_cook_update_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_cook_update_event evt;
    deserialize_chef_cook_update_event(__buffer, &evt);
    chef_waiterd_cook_update_invocation(__message, &evt);
    chef_cook_update_event_destroy(&evt);
}

void __chef_waiterd_cook_status_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_cook_build_event evt;
    deserialize_chef_cook_build_event(__buffer, &evt);
    chef_waiterd_cook_status_invocation(__message, &evt);
    chef_cook_build_event_destroy(&evt);
}

void __chef_waiterd_cook_artifact_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_cook_artifact_event evt;
    deserialize_chef_cook_artifact_event(__buffer, &evt);
    chef_waiterd_cook_artifact_invocation(__message, &evt);
    chef_cook_artifact_event_destroy(&evt);
}

int chef_waiterd_cook_event_update_request_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_cook_update_request* request)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 45);
    serialize_uint8(&__buffer, 5);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_cook_update_request(&__buffer, request);
    __status = gracht_server_send_event(server, client, &__buffer, 0);
    return __status;
}


int chef_waiterd_cook_event_update_request_all(gracht_server_t* server, const struct chef_cook_update_request* request)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 45);
    serialize_uint8(&__buffer, 5);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_cook_update_request(&__buffer, request);
    __status = gracht_server_broadcast_event(server, &__buffer, 0);
    return __status;
}


int chef_waiterd_cook_event_build_request_single(gracht_server_t* server, const gracht_conn_t client, const char* id, const struct chef_waiter_build_request* request)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 45);
    serialize_uint8(&__buffer, 6);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_string(&__buffer, id);
    serialize_chef_waiter_build_request(&__buffer, request);
    __status = gracht_server_send_event(server, client, &__buffer, 0);
    return __status;
}


int chef_waiterd_cook_event_build_request_all(gracht_server_t* server, const char* id, const struct chef_waiter_build_request* request)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 45);
    serialize_uint8(&__buffer, 6);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_string(&__buffer, id);
    serialize_chef_waiter_build_request(&__buffer, request);
    __status = gracht_server_broadcast_event(server, &__buffer, 0);
    return __status;
}


