/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_SERVED_SERVICE_CLIENT_H__
#define __CHEF_SERVED_SERVICE_CLIENT_H__

#include <gracht/client.h>

#include "chef_served_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    /**
     * Invocation callback prototypes that must be defined. These are the functions
     * that will be called when a message is received.
     */
    void chef_served_event_transaction_started_invocation(gracht_client_t* client, const struct chef_transaction_started* info);
    void chef_served_event_transaction_state_changed_invocation(gracht_client_t* client, const struct chef_transaction_state_changed* info);
    void chef_served_event_transaction_completed_invocation(gracht_client_t* client, const struct chef_transaction_completed* info);
    void chef_served_event_transaction_io_progress_invocation(gracht_client_t* client, const struct chef_transaction_io_progress* info);
    void chef_served_event_transaction_log_invocation(gracht_client_t* client, const struct chef_transaction_log* info);

    int chef_served_subscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_served_unsubscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_served_install(gracht_client_t* client, struct gracht_message_context* context, const struct chef_served_install_options* options);
    int chef_served_install_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* transaction_id_out);
    int chef_served_update(gracht_client_t* client, struct gracht_message_context* context, const struct chef_served_update_options* options);
    int chef_served_update_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* transaction_id_out);
    int chef_served_switch(gracht_client_t* client, struct gracht_message_context* context, const struct chef_served_switch_options* options);
    int chef_served_switch_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* transaction_id_out);
    int chef_served_remove(gracht_client_t* client, struct gracht_message_context* context, const char* packageName);
    int chef_served_remove_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* transaction_id_out);
    int chef_served_info(gracht_client_t* client, struct gracht_message_context* context, const char* packageName);
    int chef_served_info_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_package* info_out);
    int chef_served_listcount(gracht_client_t* client, struct gracht_message_context* context);
    int chef_served_listcount_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* count_out);
    int chef_served_list(gracht_client_t* client, struct gracht_message_context* context);
    int chef_served_list_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_package* packages_out, const uint32_t packages_count);
    int chef_served_logs(gracht_client_t* client, struct gracht_message_context* context, const unsigned int transaction_id);
    int chef_served_logs_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_transaction_log_entry* entries_out, const uint32_t entries_count);

    extern gracht_protocol_t chef_served_client_protocol;

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_SERVED_SERVICE_CLIENT_H__
