/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_SERVED_SERVICE_SERVER_H__
#define __CHEF_SERVED_SERVICE_SERVER_H__

#include <gracht/server.h>

#include "chef_served_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    /**
     * Invocation callback prototypes that must be defined. These are the functions
     * that will be called when a message is received.
     */
    void chef_served_install_invocation(struct gracht_message* message, const struct chef_served_install_options* options);
    void chef_served_update_invocation(struct gracht_message* message, const struct chef_served_update_options* options);
    void chef_served_switch_invocation(struct gracht_message* message, const struct chef_served_switch_options* options);
    void chef_served_remove_invocation(struct gracht_message* message, const char* packageName);
    void chef_served_info_invocation(struct gracht_message* message, const char* packageName);
    void chef_served_listcount_invocation(struct gracht_message* message);
    void chef_served_list_invocation(struct gracht_message* message);
    void chef_served_logs_invocation(struct gracht_message* message, const unsigned int transaction_id);

    /**
     * Response functions that can be invoked from invocations. These will format a response
     * message based on a message context.
     */
    int chef_served_install_response(struct gracht_message* message, unsigned int transaction_id);
    int chef_served_update_response(struct gracht_message* message, unsigned int transaction_id);
    int chef_served_switch_response(struct gracht_message* message, unsigned int transaction_id);
    int chef_served_remove_response(struct gracht_message* message, unsigned int transaction_id);
    int chef_served_info_response(struct gracht_message* message, struct chef_served_package* info);
    int chef_served_listcount_response(struct gracht_message* message, unsigned int count);
    int chef_served_list_response(struct gracht_message* message, struct chef_served_package* packages, uint32_t packages_count);
    int chef_served_logs_response(struct gracht_message* message, struct chef_transaction_log_entry* entries, uint32_t entries_count);

    /**
     * Event functions that can be invoked at any point in time.
     */
    int chef_served_event_transaction_started_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_started* info);
    int chef_served_event_transaction_started_all(gracht_server_t* server, const struct chef_transaction_started* info);
    int chef_served_event_transaction_state_changed_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_state_changed* info);
    int chef_served_event_transaction_state_changed_all(gracht_server_t* server, const struct chef_transaction_state_changed* info);
    int chef_served_event_transaction_completed_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_completed* info);
    int chef_served_event_transaction_completed_all(gracht_server_t* server, const struct chef_transaction_completed* info);
    int chef_served_event_transaction_io_progress_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_io_progress* info);
    int chef_served_event_transaction_io_progress_all(gracht_server_t* server, const struct chef_transaction_io_progress* info);
    int chef_served_event_transaction_log_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_log* info);
    int chef_served_event_transaction_log_all(gracht_server_t* server, const struct chef_transaction_log* info);

    extern gracht_protocol_t chef_served_server_protocol;

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_SERVED_SERVICE_SERVER_H__
