/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_WAITERD_COOK_SERVICE_CLIENT_H__
#define __CHEF_WAITERD_COOK_SERVICE_CLIENT_H__

#include <gracht/client.h>

#include "chef_waiterd_cook_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    /**
     * Invocation callback prototypes that must be defined. These are the functions
     * that will be called when a message is received.
     */
    void chef_waiterd_cook_event_update_request_invocation(gracht_client_t* client, const struct chef_cook_update_request* request);
    void chef_waiterd_cook_event_build_request_invocation(gracht_client_t* client, const char* id, const struct chef_waiter_build_request* request);

    int chef_waiterd_cook_subscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_waiterd_cook_unsubscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_waiterd_cook_ready(gracht_client_t* client, struct gracht_message_context* context, const struct chef_cook_ready_event* evt);
    int chef_waiterd_cook_update(gracht_client_t* client, struct gracht_message_context* context, const struct chef_cook_update_event* evt);
    int chef_waiterd_cook_status(gracht_client_t* client, struct gracht_message_context* context, const struct chef_cook_build_event* evt);
    int chef_waiterd_cook_artifact(gracht_client_t* client, struct gracht_message_context* context, const struct chef_cook_artifact_event* evt);

    extern gracht_protocol_t chef_waiterd_cook_client_protocol;

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_WAITERD_COOK_SERVICE_CLIENT_H__
