/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#include "chef_waiterd_cook_service_client.h"
#include <string.h>
#include <stdlib.h>


GRACHTAPI int gracht_client_get_buffer(gracht_client_t*, gracht_buffer_t*);
GRACHTAPI int gracht_client_get_status_buffer(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);
GRACHTAPI int gracht_client_status_finalize(gracht_client_t*, struct gracht_buffer*);
GRACHTAPI int gracht_client_invoke(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);

void __chef_waiterd_cook_update_request_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);
void __chef_waiterd_cook_build_request_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);

static gracht_protocol_function_t chef_waiterd_cook_callbacks[2] = {
    { SERVICE_CHEF_WAITERD_COOK_EVENT_UPDATE_REQUEST_ID, __chef_waiterd_cook_update_request_internal },
    { SERVICE_CHEF_WAITERD_COOK_EVENT_BUILD_REQUEST_ID, __chef_waiterd_cook_build_request_internal },
};

gracht_protocol_t chef_waiterd_cook_client_protocol = GRACHT_PROTOCOL_INIT(45, "chef_waiterd_cook", 2, chef_waiterd_cook_callbacks);

void __chef_waiterd_cook_update_request_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    struct chef_cook_update_request request;
    deserialize_chef_cook_update_request(__buffer, &request);
    chef_waiterd_cook_event_update_request_invocation(__client, &request);
    chef_cook_update_request_destroy(&request);
}

void __chef_waiterd_cook_build_request_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    char* id;
    struct chef_waiter_build_request request;
    id = deserialize_string_nocopy(__buffer);
    deserialize_chef_waiter_build_request(__buffer, &request);
    chef_waiterd_cook_event_build_request_invocation(__client, id, &request);
    chef_waiter_build_request_destroy(&request);
}

int chef_waiterd_cook_subscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 45);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_cook_unsubscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 45);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_cook_ready(gracht_client_t* client, struct gracht_message_context* context, const struct chef_cook_ready_event* evt) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 45);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_chef_cook_ready_event(&__buffer, evt);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_cook_update(gracht_client_t* client, struct gracht_message_context* context, const struct chef_cook_update_event* evt) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 45);
    serialize_uint8(&__buffer, 2);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_chef_cook_update_event(&__buffer, evt);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_cook_status(gracht_client_t* client, struct gracht_message_context* context, const struct chef_cook_build_event* evt) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 45);
    serialize_uint8(&__buffer, 3);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_chef_cook_build_event(&__buffer, evt);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_waiterd_cook_artifact(gracht_client_t* client, struct gracht_message_context* context, const struct chef_cook_artifact_event* evt) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 45);
    serialize_uint8(&__buffer, 4);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_chef_cook_artifact_event(&__buffer, evt);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

