/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#include "chef_cvd_service_server.h"
#include <string.h>
#include <stdlib.h>


GRACHTAPI int gracht_server_get_buffer(gracht_server_t*, gracht_buffer_t*);
GRACHTAPI int gracht_server_respond(struct gracht_message*, gracht_buffer_t*);
GRACHTAPI int gracht_server_send_event(gracht_server_t*, gracht_conn_t client, gracht_buffer_t*, unsigned int flags);
GRACHTAPI int gracht_server_broadcast_event(gracht_server_t*, gracht_buffer_t*, unsigned int flags);

void __chef_cvd_create_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_cvd_spawn_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_cvd_kill_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_cvd_upload_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_cvd_download_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_cvd_destroy_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);

static gracht_protocol_function_t chef_cvd_callbacks[6] = {
    { SERVICE_CHEF_CVD_CREATE_ID, __chef_cvd_create_internal },
    { SERVICE_CHEF_CVD_SPAWN_ID, __chef_cvd_spawn_internal },
    { SERVICE_CHEF_CVD_KILL_ID, __chef_cvd_kill_internal },
    { SERVICE_CHEF_CVD_UPLOAD_ID, __chef_cvd_upload_internal },
    { SERVICE_CHEF_CVD_DOWNLOAD_ID, __chef_cvd_download_internal },
    { SERVICE_CHEF_CVD_DESTROY_ID, __chef_cvd_destroy_internal },
};

gracht_protocol_t chef_cvd_server_protocol = GRACHT_PROTOCOL_INIT(43, "chef_cvd", 6, chef_cvd_callbacks);

void __chef_cvd_create_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_create_parameters params;
    deserialize_chef_create_parameters(__buffer, &params);
    chef_cvd_create_invocation(__message, &params);
    chef_create_parameters_destroy(&params);
}

void __chef_cvd_spawn_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_spawn_parameters params;
    deserialize_chef_spawn_parameters(__buffer, &params);
    chef_cvd_spawn_invocation(__message, &params);
    chef_spawn_parameters_destroy(&params);
}

void __chef_cvd_kill_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    char* container_id;
    unsigned int pid;
    container_id = deserialize_string_nocopy(__buffer);
    pid = deserialize_uint(__buffer);
    chef_cvd_kill_invocation(__message, container_id, pid);
}

void __chef_cvd_upload_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_file_parameters params;
    deserialize_chef_file_parameters(__buffer, &params);
    chef_cvd_upload_invocation(__message, &params);
    chef_file_parameters_destroy(&params);
}

void __chef_cvd_download_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_file_parameters params;
    deserialize_chef_file_parameters(__buffer, &params);
    chef_cvd_download_invocation(__message, &params);
    chef_file_parameters_destroy(&params);
}

void __chef_cvd_destroy_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    char* container_id;
    container_id = deserialize_string_nocopy(__buffer);
    chef_cvd_destroy_invocation(__message, container_id);
}

int chef_cvd_create_response(struct gracht_message* message, char* id, enum chef_status st)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_string(&__buffer, id);
    serialize_int(&__buffer, (int)st);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_cvd_spawn_response(struct gracht_message* message, unsigned int pid, enum chef_status st)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 2);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_uint(&__buffer, pid);
    serialize_int(&__buffer, (int)st);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_cvd_kill_response(struct gracht_message* message, enum chef_status st)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 3);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_int(&__buffer, (int)st);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_cvd_upload_response(struct gracht_message* message, enum chef_status st)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 4);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_int(&__buffer, (int)st);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_cvd_download_response(struct gracht_message* message, enum chef_status st)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 5);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_int(&__buffer, (int)st);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_cvd_destroy_response(struct gracht_message* message, enum chef_status st)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 43);
    serialize_uint8(&__buffer, 6);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_int(&__buffer, (int)st);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

