/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#include "chef_waiterd_service_server.h"
#include <string.h>
#include <stdlib.h>


GRACHTAPI int gracht_server_get_buffer(gracht_server_t*, gracht_buffer_t*);
GRACHTAPI int gracht_server_respond(struct gracht_message*, gracht_buffer_t*);
GRACHTAPI int gracht_server_send_event(gracht_server_t*, gracht_conn_t client, gracht_buffer_t*, unsigned int flags);
GRACHTAPI int gracht_server_broadcast_event(gracht_server_t*, gracht_buffer_t*, unsigned int flags);

void __chef_waiterd_build_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_waiterd_status_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_waiterd_artifact_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_waiterd_list_agents_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_waiterd_agent_info_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);

static gracht_protocol_function_t chef_waiterd_callbacks[5] = {
    { SERVICE_CHEF_WAITERD_BUILD_ID, __chef_waiterd_build_internal },
    { SERVICE_CHEF_WAITERD_STATUS_ID, __chef_waiterd_status_internal },
    { SERVICE_CHEF_WAITERD_ARTIFACT_ID, __chef_waiterd_artifact_internal },
    { SERVICE_CHEF_WAITERD_LIST_AGENTS_ID, __chef_waiterd_list_agents_internal },
    { SERVICE_CHEF_WAITERD_AGENT_INFO_ID, __chef_waiterd_agent_info_internal },
};

gracht_protocol_t chef_waiterd_server_protocol = GRACHT_PROTOCOL_INIT(44, "chef_waiterd", 5, chef_waiterd_callbacks);

void __chef_waiterd_build_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_waiter_build_request request;
    deserialize_chef_waiter_build_request(__buffer, &request);
    chef_waiterd_build_invocation(__message, &request);
    chef_waiter_build_request_destroy(&request);
}

void __chef_waiterd_status_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    char* id;
    id = deserialize_string_nocopy(__buffer);
    chef_waiterd_status_invocation(__message, id);
}

void __chef_waiterd_artifact_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    char* id;
    enum chef_artifact_type type;
    id = deserialize_string_nocopy(__buffer);
    type = (enum chef_artifact_type)deserialize_int(__buffer);
    chef_waiterd_artifact_invocation(__message, id, type);
}

void __chef_waiterd_list_agents_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    enum chef_build_architecture arch_filter;
    arch_filter = (enum chef_build_architecture)deserialize_int(__buffer);
    chef_waiterd_list_agents_invocation(__message, arch_filter);
}

void __chef_waiterd_agent_info_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    char* name;
    name = deserialize_string_nocopy(__buffer);
    chef_waiterd_agent_info_invocation(__message, name);
}

int chef_waiterd_build_response(struct gracht_message* message, enum chef_queue_status status, char* id)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_int(&__buffer, (int)status);
    serialize_string(&__buffer, id);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_waiterd_status_response(struct gracht_message* message, struct chef_waiter_status_response* response)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 2);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_chef_waiter_status_response(&__buffer, response);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_waiterd_artifact_response(struct gracht_message* message, char* link)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 3);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_string(&__buffer, link);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_waiterd_list_agents_response(struct gracht_message* message, int count, struct chef_waiter_agent_info* agents, uint32_t agents_count)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 4);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_int(&__buffer, count);
    serialize_uint32(&__buffer, agents_count);
    for (uint32_t __i = 0; __i < agents_count; __i++) {
        serialize_chef_waiter_agent_info(&__buffer, &agents[__i]);
    }
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_waiterd_agent_info_response(struct gracht_message* message, struct chef_waiter_agent_info* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 44);
    serialize_uint8(&__buffer, 5);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_chef_waiter_agent_info(&__buffer, info);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

