/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_WAITERD_SERVICE_CLIENT_H__
#define __CHEF_WAITERD_SERVICE_CLIENT_H__

#include <gracht/client.h>

#include "chef_waiterd_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    int chef_waiterd_subscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_waiterd_unsubscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_waiterd_build(gracht_client_t* client, struct gracht_message_context* context, const struct chef_waiter_build_request* request);
    int chef_waiterd_build_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_queue_status* status_out, char* id_out, const uint32_t id_max_length);
    int chef_waiterd_status(gracht_client_t* client, struct gracht_message_context* context, const char* id);
    int chef_waiterd_status_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_waiter_status_response* response_out);
    int chef_waiterd_artifact(gracht_client_t* client, struct gracht_message_context* context, const char* id, const enum chef_artifact_type type);
    int chef_waiterd_artifact_result(gracht_client_t* client, struct gracht_message_context* context, char* link_out, const uint32_t link_max_length);
    int chef_waiterd_list_agents(gracht_client_t* client, struct gracht_message_context* context, const enum chef_build_architecture arch_filter);
    int chef_waiterd_list_agents_result(gracht_client_t* client, struct gracht_message_context* context, int* count_out, struct chef_waiter_agent_info* agents_out, const uint32_t agents_count);
    int chef_waiterd_agent_info(gracht_client_t* client, struct gracht_message_context* context, const char* name);
    int chef_waiterd_agent_info_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_waiter_agent_info* info_out);

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_WAITERD_SERVICE_CLIENT_H__
