/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#include "chef_served_service_server.h"
#include <string.h>
#include <stdlib.h>


GRACHTAPI int gracht_server_get_buffer(gracht_server_t*, gracht_buffer_t*);
GRACHTAPI int gracht_server_respond(struct gracht_message*, gracht_buffer_t*);
GRACHTAPI int gracht_server_send_event(gracht_server_t*, gracht_conn_t client, gracht_buffer_t*, unsigned int flags);
GRACHTAPI int gracht_server_broadcast_event(gracht_server_t*, gracht_buffer_t*, unsigned int flags);

void __chef_served_install_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_served_update_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_served_switch_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_served_remove_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_served_info_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_served_listcount_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_served_list_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);
void __chef_served_logs_internal(struct gracht_message* __message, gracht_buffer_t* __buffer);

static gracht_protocol_function_t chef_served_callbacks[8] = {
    { SERVICE_CHEF_SERVED_INSTALL_ID, __chef_served_install_internal },
    { SERVICE_CHEF_SERVED_UPDATE_ID, __chef_served_update_internal },
    { SERVICE_CHEF_SERVED_SWITCH_ID, __chef_served_switch_internal },
    { SERVICE_CHEF_SERVED_REMOVE_ID, __chef_served_remove_internal },
    { SERVICE_CHEF_SERVED_INFO_ID, __chef_served_info_internal },
    { SERVICE_CHEF_SERVED_LISTCOUNT_ID, __chef_served_listcount_internal },
    { SERVICE_CHEF_SERVED_LIST_ID, __chef_served_list_internal },
    { SERVICE_CHEF_SERVED_LOGS_ID, __chef_served_logs_internal },
};

gracht_protocol_t chef_served_server_protocol = GRACHT_PROTOCOL_INIT(42, "chef_served", 8, chef_served_callbacks);

void __chef_served_install_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_served_install_options options;
    deserialize_chef_served_install_options(__buffer, &options);
    chef_served_install_invocation(__message, &options);
    chef_served_install_options_destroy(&options);
}

void __chef_served_update_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_served_update_options options;
    deserialize_chef_served_update_options(__buffer, &options);
    chef_served_update_invocation(__message, &options);
    chef_served_update_options_destroy(&options);
}

void __chef_served_switch_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    struct chef_served_switch_options options;
    deserialize_chef_served_switch_options(__buffer, &options);
    chef_served_switch_invocation(__message, &options);
    chef_served_switch_options_destroy(&options);
}

void __chef_served_remove_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    char* packageName;
    packageName = deserialize_string_nocopy(__buffer);
    chef_served_remove_invocation(__message, packageName);
}

void __chef_served_info_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    char* packageName;
    packageName = deserialize_string_nocopy(__buffer);
    chef_served_info_invocation(__message, packageName);
}

void __chef_served_listcount_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    chef_served_listcount_invocation(__message);
}

void __chef_served_list_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    chef_served_list_invocation(__message);
}

void __chef_served_logs_internal(struct gracht_message* __message, gracht_buffer_t* __buffer)
{
    unsigned int transaction_id;
    transaction_id = deserialize_uint(__buffer);
    chef_served_logs_invocation(__message, transaction_id);
}

int chef_served_install_response(struct gracht_message* message, unsigned int transaction_id)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_uint(&__buffer, transaction_id);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_served_update_response(struct gracht_message* message, unsigned int transaction_id)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 2);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_uint(&__buffer, transaction_id);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_served_switch_response(struct gracht_message* message, unsigned int transaction_id)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 3);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_uint(&__buffer, transaction_id);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_served_remove_response(struct gracht_message* message, unsigned int transaction_id)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 4);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_uint(&__buffer, transaction_id);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_served_info_response(struct gracht_message* message, struct chef_served_package* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 5);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_chef_served_package(&__buffer, info);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_served_listcount_response(struct gracht_message* message, unsigned int count)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 6);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_uint(&__buffer, count);
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_served_list_response(struct gracht_message* message, struct chef_served_package* packages, uint32_t packages_count)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 7);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_uint32(&__buffer, packages_count);
    for (uint32_t __i = 0; __i < packages_count; __i++) {
        serialize_chef_served_package(&__buffer, &packages[__i]);
    }
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_served_logs_response(struct gracht_message* message, struct chef_transaction_log_entry* entries, uint32_t entries_count)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(message->server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 8);
    serialize_uint8(&__buffer, MESSAGE_FLAG_RESPONSE);
    serialize_uint32(&__buffer, entries_count);
    for (uint32_t __i = 0; __i < entries_count; __i++) {
        serialize_chef_transaction_log_entry(&__buffer, &entries[__i]);
    }
    __status = gracht_server_respond(message, &__buffer);
    return __status;
}

int chef_served_event_transaction_started_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_started* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 9);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_started(&__buffer, info);
    __status = gracht_server_send_event(server, client, &__buffer, 0);
    return __status;
}


int chef_served_event_transaction_started_all(gracht_server_t* server, const struct chef_transaction_started* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 9);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_started(&__buffer, info);
    __status = gracht_server_broadcast_event(server, &__buffer, 0);
    return __status;
}


int chef_served_event_transaction_state_changed_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_state_changed* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 10);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_state_changed(&__buffer, info);
    __status = gracht_server_send_event(server, client, &__buffer, 0);
    return __status;
}


int chef_served_event_transaction_state_changed_all(gracht_server_t* server, const struct chef_transaction_state_changed* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 10);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_state_changed(&__buffer, info);
    __status = gracht_server_broadcast_event(server, &__buffer, 0);
    return __status;
}


int chef_served_event_transaction_completed_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_completed* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 11);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_completed(&__buffer, info);
    __status = gracht_server_send_event(server, client, &__buffer, 0);
    return __status;
}


int chef_served_event_transaction_completed_all(gracht_server_t* server, const struct chef_transaction_completed* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 11);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_completed(&__buffer, info);
    __status = gracht_server_broadcast_event(server, &__buffer, 0);
    return __status;
}


int chef_served_event_transaction_io_progress_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_io_progress* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 12);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_io_progress(&__buffer, info);
    __status = gracht_server_send_event(server, client, &__buffer, 0);
    return __status;
}


int chef_served_event_transaction_io_progress_all(gracht_server_t* server, const struct chef_transaction_io_progress* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 12);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_io_progress(&__buffer, info);
    __status = gracht_server_broadcast_event(server, &__buffer, 0);
    return __status;
}


int chef_served_event_transaction_log_single(gracht_server_t* server, const gracht_conn_t client, const struct chef_transaction_log* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 13);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_log(&__buffer, info);
    __status = gracht_server_send_event(server, client, &__buffer, 0);
    return __status;
}


int chef_served_event_transaction_log_all(gracht_server_t* server, const struct chef_transaction_log* info)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_server_get_buffer(server, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 13);
    serialize_uint8(&__buffer, MESSAGE_FLAG_EVENT);
    serialize_chef_transaction_log(&__buffer, info);
    __status = gracht_server_broadcast_event(server, &__buffer, 0);
    return __status;
}


