/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#include "chef_served_service_client.h"
#include <string.h>
#include <stdlib.h>


GRACHTAPI int gracht_client_get_buffer(gracht_client_t*, gracht_buffer_t*);
GRACHTAPI int gracht_client_get_status_buffer(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);
GRACHTAPI int gracht_client_status_finalize(gracht_client_t*, struct gracht_buffer*);
GRACHTAPI int gracht_client_invoke(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);

void __chef_served_transaction_started_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);
void __chef_served_transaction_state_changed_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);
void __chef_served_transaction_completed_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);
void __chef_served_transaction_io_progress_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);
void __chef_served_transaction_log_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);

static gracht_protocol_function_t chef_served_callbacks[5] = {
    { SERVICE_CHEF_SERVED_EVENT_TRANSACTION_STARTED_ID, __chef_served_transaction_started_internal },
    { SERVICE_CHEF_SERVED_EVENT_TRANSACTION_STATE_CHANGED_ID, __chef_served_transaction_state_changed_internal },
    { SERVICE_CHEF_SERVED_EVENT_TRANSACTION_COMPLETED_ID, __chef_served_transaction_completed_internal },
    { SERVICE_CHEF_SERVED_EVENT_TRANSACTION_IO_PROGRESS_ID, __chef_served_transaction_io_progress_internal },
    { SERVICE_CHEF_SERVED_EVENT_TRANSACTION_LOG_ID, __chef_served_transaction_log_internal },
};

gracht_protocol_t chef_served_client_protocol = GRACHT_PROTOCOL_INIT(42, "chef_served", 5, chef_served_callbacks);

void __chef_served_transaction_started_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    struct chef_transaction_started info;
    deserialize_chef_transaction_started(__buffer, &info);
    chef_served_event_transaction_started_invocation(__client, &info);
    chef_transaction_started_destroy(&info);
}

void __chef_served_transaction_state_changed_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    struct chef_transaction_state_changed info;
    deserialize_chef_transaction_state_changed(__buffer, &info);
    chef_served_event_transaction_state_changed_invocation(__client, &info);
    chef_transaction_state_changed_destroy(&info);
}

void __chef_served_transaction_completed_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    struct chef_transaction_completed info;
    deserialize_chef_transaction_completed(__buffer, &info);
    chef_served_event_transaction_completed_invocation(__client, &info);
    chef_transaction_completed_destroy(&info);
}

void __chef_served_transaction_io_progress_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    struct chef_transaction_io_progress info;
    deserialize_chef_transaction_io_progress(__buffer, &info);
    chef_served_event_transaction_io_progress_invocation(__client, &info);
    chef_transaction_io_progress_destroy(&info);
}

void __chef_served_transaction_log_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    struct chef_transaction_log info;
    deserialize_chef_transaction_log(__buffer, &info);
    chef_served_event_transaction_log_invocation(__client, &info);
    chef_transaction_log_destroy(&info);
}

int chef_served_subscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 42);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_unsubscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 42);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_install(gracht_client_t* client, struct gracht_message_context* context, const struct chef_served_install_options* options) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_chef_served_install_options(&__buffer, options);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_install_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* transaction_id_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *transaction_id_out = deserialize_uint(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_update(gracht_client_t* client, struct gracht_message_context* context, const struct chef_served_update_options* options) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 2);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_chef_served_update_options(&__buffer, options);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_update_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* transaction_id_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *transaction_id_out = deserialize_uint(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_switch(gracht_client_t* client, struct gracht_message_context* context, const struct chef_served_switch_options* options) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 3);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_chef_served_switch_options(&__buffer, options);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_switch_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* transaction_id_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *transaction_id_out = deserialize_uint(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_remove(gracht_client_t* client, struct gracht_message_context* context, const char* packageName) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 4);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, packageName);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_remove_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* transaction_id_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *transaction_id_out = deserialize_uint(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_info(gracht_client_t* client, struct gracht_message_context* context, const char* packageName) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 5);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, packageName);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_info_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_package* info_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    deserialize_chef_served_package(&__buffer, info_out);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_listcount(gracht_client_t* client, struct gracht_message_context* context) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 6);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_listcount_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* count_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *count_out = deserialize_uint(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_list(gracht_client_t* client, struct gracht_message_context* context) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 7);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_list_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_package* packages_out, const uint32_t packages_count) {
    gracht_buffer_t __buffer;
    int __status;
    uint32_t __count;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    __count = deserialize_uint32(&__buffer);
    for (uint32_t __i = 0; __i < GRMIN(__count, packages_count); __i++) {
        deserialize_chef_served_package(&__buffer, &packages_out[__i]);
    }
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_logs(gracht_client_t* client, struct gracht_message_context* context, const unsigned int transaction_id) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 8);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_uint(&__buffer, transaction_id);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_logs_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_transaction_log_entry* entries_out, const uint32_t entries_count) {
    gracht_buffer_t __buffer;
    int __status;
    uint32_t __count;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    __count = deserialize_uint32(&__buffer);
    for (uint32_t __i = 0; __i < GRMIN(__count, entries_count); __i++) {
        deserialize_chef_transaction_log_entry(&__buffer, &entries_out[__i]);
    }
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

