/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#include "chef_served_service_client.h"
#include <string.h>
#include <stdlib.h>


GRACHTAPI int gracht_client_get_buffer(gracht_client_t*, gracht_buffer_t*);
GRACHTAPI int gracht_client_get_status_buffer(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);
GRACHTAPI int gracht_client_status_finalize(gracht_client_t*, struct gracht_buffer*);
GRACHTAPI int gracht_client_invoke(gracht_client_t*, struct gracht_message_context*, gracht_buffer_t*);

void __chef_served_package_installed_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);
void __chef_served_package_removed_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);
void __chef_served_package_updated_internal(gracht_client_t* __client, gracht_buffer_t* __buffer);

static gracht_protocol_function_t chef_served_callbacks[3] = {
    { SERVICE_CHEF_SERVED_EVENT_PACKAGE_INSTALLED_ID, __chef_served_package_installed_internal },
    { SERVICE_CHEF_SERVED_EVENT_PACKAGE_REMOVED_ID, __chef_served_package_removed_internal },
    { SERVICE_CHEF_SERVED_EVENT_PACKAGE_UPDATED_ID, __chef_served_package_updated_internal },
};

gracht_protocol_t chef_served_client_protocol = GRACHT_PROTOCOL_INIT(42, "chef_served", 3, chef_served_callbacks);

void __chef_served_package_installed_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    enum chef_install_status status;
    struct chef_served_package info;
    status = (enum chef_install_status)deserialize_int(__buffer);
    deserialize_chef_served_package(__buffer, &info);
    chef_served_event_package_installed_invocation(__client, status, &info);
    chef_served_package_destroy(&info);
}

void __chef_served_package_removed_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    struct chef_served_package info;
    deserialize_chef_served_package(__buffer, &info);
    chef_served_event_package_removed_invocation(__client, &info);
    chef_served_package_destroy(&info);
}

void __chef_served_package_updated_internal(gracht_client_t* __client, gracht_buffer_t* __buffer)
{
    enum chef_update_status status;
    struct chef_served_package info;
    status = (enum chef_update_status)deserialize_int(__buffer);
    deserialize_chef_served_package(__buffer, &info);
    chef_served_event_package_updated_invocation(__client, status, &info);
    chef_served_package_destroy(&info);
}

int chef_served_subscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 42);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_unsubscribe(gracht_client_t* client, struct gracht_message_context* context)
{
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 0);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_uint8(&__buffer, 42);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_install(gracht_client_t* client, struct gracht_message_context* context, const char* publisher, const char* path) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 1);
    serialize_uint8(&__buffer, MESSAGE_FLAG_ASYNC);
    serialize_string(&__buffer, publisher);
    serialize_string(&__buffer, path);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_remove(gracht_client_t* client, struct gracht_message_context* context, const char* packageName) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 2);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, packageName);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_remove_result(gracht_client_t* client, struct gracht_message_context* context, int* result_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *result_out = deserialize_int(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_info(gracht_client_t* client, struct gracht_message_context* context, const char* packageName) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 3);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, packageName);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_info_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_package* info_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    deserialize_chef_served_package(&__buffer, info_out);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_listcount(gracht_client_t* client, struct gracht_message_context* context) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 4);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_listcount_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* count_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    *count_out = deserialize_uint(&__buffer);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_list(gracht_client_t* client, struct gracht_message_context* context) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 5);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_list_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_package* packages_out, const uint32_t packages_count) {
    gracht_buffer_t __buffer;
    int __status;
    uint32_t __count;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    __count = deserialize_uint32(&__buffer);
    for (uint32_t __i = 0; __i < GRMIN(__count, packages_count); __i++) {
        deserialize_chef_served_package(&__buffer, &packages_out[__i]);
    }
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

int chef_served_get_command(gracht_client_t* client, struct gracht_message_context* context, const char* mountPath) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_buffer(client, &__buffer);
    if (__status) {
        return __status;
    }
    
    serialize_uint32(&__buffer, 0);
    serialize_uint32(&__buffer, 0);
    serialize_uint8(&__buffer, 42);
    serialize_uint8(&__buffer, 6);
    serialize_uint8(&__buffer, MESSAGE_FLAG_SYNC);
    serialize_string(&__buffer, mountPath);
    __status = gracht_client_invoke(client, context, &__buffer);
    return __status;
}

int chef_served_get_command_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_command* command_out) {
    gracht_buffer_t __buffer;
    int __status;
    
    __status = gracht_client_get_status_buffer(client, context, &__buffer);
    if (__status != GRACHT_MESSAGE_COMPLETED) {
        return __status;
    }
    
    deserialize_chef_served_command(&__buffer, command_out);
    __status = gracht_client_status_finalize(client, &__buffer);
    return __status;
}

