/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_SERVED_SERVICE_CLIENT_H__
#define __CHEF_SERVED_SERVICE_CLIENT_H__

#include <gracht/client.h>

#include "chef_served_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    /**
     * Invocation callback prototypes that must be defined. These are the functions
     * that will be called when a message is received.
     */
    void chef_served_event_package_installed_invocation(gracht_client_t* client, const enum chef_install_status status, const struct chef_served_package* info);
    void chef_served_event_package_removed_invocation(gracht_client_t* client, const struct chef_served_package* info);
    void chef_served_event_package_updated_invocation(gracht_client_t* client, const enum chef_update_status status, const struct chef_served_package* info);

    int chef_served_subscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_served_unsubscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_served_install(gracht_client_t* client, struct gracht_message_context* context, const char* publisher, const char* path);
    int chef_served_remove(gracht_client_t* client, struct gracht_message_context* context, const char* packageName);
    int chef_served_remove_result(gracht_client_t* client, struct gracht_message_context* context, int* result_out);
    int chef_served_info(gracht_client_t* client, struct gracht_message_context* context, const char* packageName);
    int chef_served_info_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_package* info_out);
    int chef_served_listcount(gracht_client_t* client, struct gracht_message_context* context);
    int chef_served_listcount_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* count_out);
    int chef_served_list(gracht_client_t* client, struct gracht_message_context* context);
    int chef_served_list_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_package* packages_out, const uint32_t packages_count);
    int chef_served_get_command(gracht_client_t* client, struct gracht_message_context* context, const char* mountPath);
    int chef_served_get_command_result(gracht_client_t* client, struct gracht_message_context* context, struct chef_served_command* command_out);

    extern gracht_protocol_t chef_served_client_protocol;

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_SERVED_SERVICE_CLIENT_H__
