/**
* This file was generated by the gracht service generator script. Any changes done here will be overwritten.
 */

#ifndef __CHEF_CVD_SERVICE_CLIENT_H__
#define __CHEF_CVD_SERVICE_CLIENT_H__

#include <gracht/client.h>

#include "chef_cvd_service.h"
#ifdef __cplusplus
extern "C" {
#endif //! __cplusplus
    int chef_cvd_subscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_cvd_unsubscribe(gracht_client_t* client, struct gracht_message_context* context);
    int chef_cvd_create(gracht_client_t* client, struct gracht_message_context* context, const struct chef_create_parameters* params);
    int chef_cvd_create_result(gracht_client_t* client, struct gracht_message_context* context, char* id_out, const uint32_t id_max_length, enum chef_status* st_out);
    int chef_cvd_spawn(gracht_client_t* client, struct gracht_message_context* context, const struct chef_spawn_parameters* params);
    int chef_cvd_spawn_result(gracht_client_t* client, struct gracht_message_context* context, unsigned int* pid_out, enum chef_status* st_out);
    int chef_cvd_kill(gracht_client_t* client, struct gracht_message_context* context, const char* container_id, const unsigned int pid);
    int chef_cvd_kill_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_status* st_out);
    int chef_cvd_upload(gracht_client_t* client, struct gracht_message_context* context, const struct chef_file_parameters* params);
    int chef_cvd_upload_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_status* st_out);
    int chef_cvd_download(gracht_client_t* client, struct gracht_message_context* context, const struct chef_file_parameters* params);
    int chef_cvd_download_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_status* st_out);
    int chef_cvd_destroy(gracht_client_t* client, struct gracht_message_context* context, const char* container_id);
    int chef_cvd_destroy_result(gracht_client_t* client, struct gracht_message_context* context, enum chef_status* st_out);

#ifdef __cplusplus
}
#endif //! __cplusplus

#endif //! __CHEF_CVD_SERVICE_CLIENT_H__
