project: 
  summary: The linux OS base
  description: |
    This is the base OS linux ingredient, which is used as the base for all
    other chef packages built for linux.
  author: Philip Meulengracht
  email: the_meulengracht@hotmail.com
  version: 1.0.0
  license: MIT

environment:
  host:
    packages:
      - ca-certificates
      - wget
      - tar

recipes:
  - name: base
    source:
      type: path
      path: ./
      script: |
        if build.subsystem.platform_host() == "linux" then
          build.shell("construct.sh", "$[[ INSTALL_PREFIX ]] $[[ CHEF_TARGET_ARCHITECTURE ]]")
        end

packs:
- name: linux-base
  type: os
