name: ubuntu-24
author: Philip Meulengracht
email: the_meulengracht@hotmail.com
version: 1.0.0
license: MIT

environment:
  host:
    packages:
      - ca-certificates
      - wget
      - tar

recipes:
  - name: ubuntu-rootfs
    source:
      type: path
      path: ./
      script: |
        if build.subsystem.platform_host() == "linux" then
          args = build.paths.install()
          args = args .. " " .. build.subsystem.arch_target()
          build.shell("construct.sh", args)
        end

packs:
- name: ubuntu-24
  summary: The Ubuntu 24.04 base
  description: |
    This is the Ubuntu 24.04 OS base, which is the default base for all
    other chef packages built for linux.
  type: os
