# Chef Container Orchestration - Microservices Example
version: '1.0'
name: 'microservices-app'

services:
  user-service:
    image: user-service:v1.2
    ports:
      - "8001:8080"
    environment:
      - DATABASE_URL=postgresql://users:password@postgres:5432/users_db
      - JWT_SECRET=supersecret123
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    restart: on-failure
    replicas: 3
    depends_on:
      - postgres
      
  product-service:
    image: product-service:v1.1
    ports:
      - "8002:8080"
    environment:
      - DATABASE_URL=postgresql://products:password@postgres:5432/products_db
      - CACHE_URL=redis://redis:6379/1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    restart: on-failure
    replicas: 2
    depends_on:
      - postgres
      - redis
      
  order-service:
    image: order-service:v1.0
    ports:
      - "8003:8080"
    environment:
      - DATABASE_URL=postgresql://orders:password@postgres:5432/orders_db
      - USER_SERVICE_URL=http://user-service:8080
      - PRODUCT_SERVICE_URL=http://product-service:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 20s
      timeout: 5s
      retries: 3
    restart: on-failure
    replicas: 2
    depends_on:
      - user-service
      - product-service
      
  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./gateway.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - product-service  
      - order-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    replicas: 2
    
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=microservices
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d microservices"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always
    replicas: 1
    
  redis:
    image: redis:alpine
    command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
    replicas: 1

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    driver: bridge
    subnet: 172.20.0.0/16
    gateway: 172.20.0.1