# Chef Container Orchestration - Web Application Example
version: '1.0'
name: 'web-application'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=webapp
      - POSTGRES_USER=webuser
      - POSTGRES_PASSWORD=secret123
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webuser -d webapp"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    replicas: 1
    
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
    replicas: 1
    
  api:
    image: webapp-api:latest
    environment:
      - DATABASE_URL=postgresql://webuser:secret123@database:5432/webapp
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    ports:
      - "8080"
    depends_on:
      - database
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: on-failure
    replicas: 2
    
  worker:
    image: webapp-api:latest
    command: ["npm", "run", "worker"]
    environment:
      - DATABASE_URL=postgresql://webuser:secret123@database:5432/webapp
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - database
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always
    replicas: 1
    
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    replicas: 2

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    driver: bridge
    
secrets:
  db_password:
    file: ./secrets/db_password.txt
  ssl_cert:
    file: ./secrets/ssl_certificate.pem
  ssl_key:
    file: ./secrets/ssl_private_key.pem