/**
 * Copyright 2024, Philip Meulengracht
 *
 * This program is free software : you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation ? , either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * 
 */

#include <errno.h>
#include <chef/kitchen.h>
#include <chef/platform.h>
#include <fcntl.h>
#include <libingredient.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <vlog.h>

static char* __string_array_join(const char* const* items, const char* prefix, const char* separator)
{
    char* buffer;

    buffer = calloc(4096, 1); 
    if (buffer == NULL) {
        return NULL;
    }

    for (int i = 0; items[i]; i++) {
        if (buffer[0] == 0) {
            strcpy(buffer, prefix);
        } else {
            strcat(buffer, separator);
            strcat(buffer, prefix);
        }
        strcat(buffer, items[i]);
    }
    return buffer;
}

static int __make_available(const char* hostRoot, const char* root, struct ingredient* ingredient)
{
    FILE* file;
    char  pcName[256];
    char* pcPath;
    int   written;
    int   status;
    char* cflags;
    char* libs;

    if (ingredient->options == NULL) {
        // Can't add a pkg-config file if the ingredient didn't specify any
        // options for consumers.
        // TODO: Add defaults?
        return 0;
    }

    // The package name specified on the pkg-config command line is defined 
    // to be the name of the metadata file, minus the .pc extension. Optionally
    // the version can be appended as name-1.0
    written = snprintf(&pcName[0], sizeof(pcName) - 1, "%s.pc", ingredient->package->package);
    if (written == (sizeof(pcName) - 1)) {
        errno = E2BIG;
        return -1;
    }
    
    pcPath = strpathjoin(hostRoot, "/usr/share/pkgconfig/", &pcName[0], NULL);
    if (pcPath == NULL) {
        return -1;
    }
    
    file = fopen(pcPath, "w");
    if(!file) {
        VLOG_ERROR("kitchen", "__make_available: failed to open %s for writing: %s\n", pcPath, strerror(errno));
        free(pcPath);
        return -1;
    }

    cflags = __string_array_join((const char* const*)ingredient->options->inc_dirs, "-I{prefix}", " ");
    libs = __string_array_join((const char* const*)ingredient->options->lib_dirs, "-L{prefix}", " ");
    if (cflags == NULL || libs == NULL) {
        free(cflags);
        free(libs);
        fclose(file);
        return -1;
    }

    fprintf(file, "# generated by chef, please do not manually modify this\n");
    fprintf(file, "prefix=%s\n", root);

    fprintf(file, "Name: %s\n", ingredient->package->package);
    fprintf(file, "Description: %s by %s\n", ingredient->package->package, ingredient->package->publisher);
    fprintf(file, "Version: %i.%i.%i\n", ingredient->version->major, ingredient->version->minor, ingredient->version->patch);
    fprintf(file, "Cflags: %s\n", cflags);
    fprintf(file, "Libs: %s\n", libs);
    free(cflags);
    free(libs);
    return fclose(file);
}

static int __setup_ingredient(struct list* ingredients, const char* hostPath, const char* chrootPath)
{
    struct list_item* i;
    int               status;

    if (ingredients == NULL) {
        return 0;
    }

    list_foreach(ingredients, i) {
        struct kitchen_ingredient* kitchenIngredient = (struct kitchen_ingredient*)i;
        struct ingredient*         ingredient;

        status = ingredient_open(kitchenIngredient->path, &ingredient);
        if (status) {
            VLOG_ERROR("kitchen", "__setup_ingredients: failed to open %s\n", kitchenIngredient->name);
            return -1;
        }

        // Only unpack ingredients, we may encounter toolchains here.
        if (ingredient->package->type != CHEF_PACKAGE_TYPE_INGREDIENT) {
            VLOG_TRACE("kitchen", "__setup_ingredients: skipping %s of type %i", kitchenIngredient->name, ingredient->package->type);
            ingredient_close(ingredient);
            continue;
        }

        status = ingredient_unpack(ingredient, hostPath, NULL, NULL);
        if (status) {
            ingredient_close(ingredient);
            VLOG_ERROR("kitchen", "__setup_ingredients: failed to setup %s\n", kitchenIngredient->name);
            return -1;
        }

        status = __make_available(hostPath, chrootPath, ingredient);
        ingredient_close(ingredient);
        if (status) {
            VLOG_ERROR("kitchen", "__setup_ingredients: failed to make %s available\n", kitchenIngredient->name);
            return -1;
        }
    }
    return 0;
}

static int __setup_toolchains(struct list* ingredients, const char* hostPath)
{
    struct list_item* i;
    int               status;
    char              buff[512];

    if (ingredients == NULL) {
        return 0;
    }

    list_foreach(ingredients, i) {
        struct kitchen_ingredient* kitchenIngredient = (struct kitchen_ingredient*)i;
        struct ingredient*         ingredient;

        status = ingredient_open(kitchenIngredient->path, &ingredient);
        if (status) {
            VLOG_ERROR("kitchen", "__setup_toolchains: failed to open %s\n", kitchenIngredient->name);
            return -1;
        }

        if (ingredient->package->type != CHEF_PACKAGE_TYPE_TOOLCHAIN) {
            ingredient_close(ingredient);
            continue;
        }

        snprintf(&buff[0], sizeof(buff), "%s/%s", hostPath, kitchenIngredient->name);
        if (platform_mkdir(&buff[0])) {
            VLOG_ERROR("kitchen", "__setup_toolchains: failed to create %s\n", &buff[0]);
            return -1;
        }

        status = ingredient_unpack(ingredient, &buff[0], NULL, NULL);
        if (status) {
            ingredient_close(ingredient);
            VLOG_ERROR("kitchen", "__setup_toolchains: failed to setup %s\n", kitchenIngredient->name);
            return -1;
        }
        ingredient_close(ingredient);
    }
    return 0;
}

static int __setup_ingredients(struct kitchen* kitchen, struct kitchen_options* options)
{
    int status;

    status = __setup_ingredient(&options->host_ingredients, kitchen->host_chroot, ".");
    if (status) {
        return status;
    }

    status = __setup_ingredient(&options->build_ingredients, kitchen->host_build_ingredients_path, kitchen->build_ingredients_path);
    if (status) {
        return status;
    }

    status = __setup_toolchains(&options->build_ingredients, kitchen->host_build_toolchains_path);
    if (status) {
        return status;
    }

    status = __setup_ingredient(&options->runtime_ingredients, kitchen->host_install_path, kitchen->install_root);
    if (status) {
        return status;
    }
    return 0;
}

static unsigned int __hash(unsigned int hash, const char* data, size_t length)
{
    for (unsigned int i = 0; i < length; i++) {
        unsigned char c = (unsigned char)data[i];
        hash = ((hash << 5) + hash) + c;
    }
    return hash;
}

static unsigned int __hash_ingredients(struct list* ingredients, unsigned int seed)
{
    unsigned int      hash = seed;
    struct list_item* i;

    list_foreach(ingredients, i) {
        struct kitchen_ingredient* ing = (struct kitchen_ingredient*)i;
        hash = __hash(hash, ing->name, strlen(ing->name));
    }
    return hash;
}

// hash of ingredients and imports
static unsigned int __setup_hash(struct kitchen_options* options)
{
    unsigned int hash = 5381;

    // hash name
    hash = __hash(hash, options->name, strlen(options->name));

    // hash ingredients
    hash = __hash_ingredients(&options->host_ingredients, hash);
    hash = __hash_ingredients(&options->build_ingredients, hash);
    hash = __hash_ingredients(&options->runtime_ingredients, hash);
    return hash;
}

static unsigned int __read_hash(const char* name)
{
    char  buff[512];
    FILE* hashFile;
    long  size;
    char* end = NULL;
    VLOG_TRACE("kitchen", "__read_hash()\n");

    snprintf(&buff[0], sizeof(buff), ".kitchen/%s/chef/.hash", name);
    hashFile = fopen(&buff[0], "r");
    if (hashFile == NULL) {
        VLOG_TRACE("kitchen", "__read_hash: no hash file\n");
        return 0;
    }

    fseek(hashFile, 0, SEEK_END);
    size = ftell(hashFile);
    rewind(hashFile);

    if (size >= sizeof(buff)) {
        VLOG_ERROR("kitchen", "__read_hash: the hash file was invalid\n");
        fclose(hashFile);
        return 0;
    }
    if (fread(&buff[0], 1, size, hashFile) < size) {
        VLOG_ERROR("kitchen", "__read_hash: failed to read hash file\n");
        fclose(hashFile);
        return 0;
    }
    
    fclose(hashFile);
    return (unsigned int)strtoul(&buff[0], &end, 10);
}

static int __write_hash(struct kitchen_options* options)
{
    char         kitchenPad[512];
    FILE*        hashFile;
    unsigned int hash;
    VLOG_TRACE("kitchen", "__write_hash(name=%s)\n", options->name);

    snprintf(&kitchenPad[0], sizeof(kitchenPad), ".kitchen/%s/chef/.hash", options->name);
    hashFile = fopen(&kitchenPad[0], "w");
    if (hashFile == NULL) {
        VLOG_TRACE("kitchen", "__read_hash: no hash file");
        return 0;
    }

    hash = __setup_hash(options);
    fprintf(hashFile, "%u", hash);
    fclose(hashFile);
    return 0;
}

static int __should_skip_setup(struct kitchen_options* options)
{
    unsigned int currentHash  = __setup_hash(options);
    unsigned int existingHash = __read_hash(options->name);
    return currentHash == existingHash;
}

// <root>/.kitchen/output
// <root>/.kitchen/<recipe>/bin
// <root>/.kitchen/<recipe>/lib
// <root>/.kitchen/<recipe>/share
// <root>/.kitchen/<recipe>/usr/...
// <root>/.kitchen/<recipe>/chef/build
// <root>/.kitchen/<recipe>/chef/build/ingredients
// <root>/.kitchen/<recipe>/chef/build/toolchains
// <root>/.kitchen/<recipe>/chef/install => <root>/.kitchen/output
// <root>/.kitchen/<recipe>/chef/project => <root>
static int __kitchen_construct(struct kitchen_options* options, struct kitchen* kitchen)
{
    char buff[512];
    VLOG_DEBUG("kitchen", "__kitchen_construct(name=%s)\n", options->name);

    snprintf(&buff[0], sizeof(buff), ".kitchen/%s", options->name);
    kitchen->host_chroot = strdup(&buff[0]);

    snprintf(&buff[0], sizeof(buff), ".kitchen/%s/chef/build", options->name);
    kitchen->host_build_path = strdup(&buff[0]);

    snprintf(&buff[0], sizeof(buff), ".kitchen/%s/chef/build/ingredients", options->name);
    kitchen->host_build_ingredients_path = strdup(&buff[0]);

    snprintf(&buff[0], sizeof(buff), ".kitchen/%s/chef/build/toolchains", options->name);
    kitchen->host_build_toolchains_path = strdup(&buff[0]);

    snprintf(&buff[0], sizeof(buff), ".kitchen/%s/chef/project", options->name);
    kitchen->host_project_path = strdup(&buff[0]);

    snprintf(&buff[0], sizeof(buff), ".kitchen/%s/chef/install", options->name);
    kitchen->host_install_path = strdup(&buff[0]);

    snprintf(&buff[0], sizeof(buff), ".kitchen/%s/chef/.checkpoint", options->name);
    kitchen->host_checkpoint_path = strdup(&buff[0]);

    kitchen->project_root = strdup("/chef/project");
    kitchen->build_root = strdup("/chef/build");
    kitchen->build_ingredients_path = strdup("/chef/build/ingredients");
    kitchen->build_toolchains_path = strdup("/chef/build/toolchains");
    kitchen->install_root = strdup("/chef/install");
    kitchen->confined = options->confined;
    return 0;
}

int kitchen_setup(struct kitchen_options* options, struct kitchen* kitchen)
{
    VLOG_DEBUG("kitchen", "kitchen_setup(name=%s)\n", options->name);

    if (__kitchen_construct(options, kitchen)) {
        return -1;
    }

    if (__should_skip_setup(options)) {
        return 0;
    }

    if (platform_mkdir(kitchen->host_build_ingredients_path)) {
        VLOG_ERROR("kitchen", "kitchen_setup: failed to create %s\n", kitchen->host_build_ingredients_path);
        return -1;
    }

    if (platform_mkdir(kitchen->host_build_toolchains_path)) {
        VLOG_ERROR("kitchen", "kitchen_setup: failed to create %s\n", kitchen->host_build_toolchains_path);
        return -1;
    }

    if (platform_symlink(kitchen->host_install_path, ".kitchen/output", 1)) {
        VLOG_ERROR("kitchen", "kitchen_setup: failed to link %s\n", kitchen->host_install_path);
        return -1;
    }

    if (platform_symlink(kitchen->host_project_path, options->project_path, 1)) {
        VLOG_ERROR("kitchen", "kitchen_setup: failed to link %s\n", kitchen->host_project_path);
        return -1;
    }

    // extract os/ingredients/toolchain
    if (__setup_ingredients(kitchen, options)) {
        return -1;
    }

    // write hash
    if (__write_hash(options)) {
        return -1;
    }
    return 0;
}

int kitchen_enter(struct kitchen* kitchen)
{
    VLOG_DEBUG("kitchen", "kitchen_enter(confined=%i)\n", kitchen->confined);
    
    if (!kitchen->confined) {
        // for an unconfined we do not chroot, instead we allow full access
        // to the base operating system to allow the the part to include all
        // it needs.
        return 0;
    }

    if (kitchen->original_root_fd > 0) {
        VLOG_ERROR("kitchen", "kitchen_enter: cannot recursively enter kitchen root\n");
        return -1;
    }

    kitchen->original_root_fd = open("/", __O_PATH);
    if (kitchen->original_root_fd < 0) {
        VLOG_ERROR("kitchen", "kitchen_enter: failed to get a handle on root: %s\n", strerror(errno));
        return -1;
    }

    if (chroot(kitchen->host_chroot)) {
        VLOG_ERROR("kitchen", "kitchen_enter: failed to change root environment to %s\n", kitchen->host_chroot);
        return -1;
    }

    // Change working directory to the known project root
    if (chdir(kitchen->project_root)) {
        VLOG_ERROR("kitchen", "kitchen_enter: failed to change working directory to %s\n", kitchen->project_root);
        return -1;
    }
    return 0;
}

int kitchen_leave(struct kitchen* kitchen)
{
    VLOG_DEBUG("kitchen", "kitchen_leave()\n");

    if (!kitchen->confined) {
        // nothing to do for unconfined
        return 0;
    }
    
    if (kitchen->original_root_fd <= 0) {
        return -1;
    }

    if (fchdir(kitchen->original_root_fd)) {
        return -1;
    }
    if (chroot(".")) {
        return -1;
    }
    close(kitchen->original_root_fd);
    kitchen->original_root_fd = 0;
    return 0;
}

static int __reset_steps(struct list* steps, enum recipe_step_type stepType, const char* name);

static int __step_depends_on(struct list* dependencies, const char* step)
{
    struct list_item* item;
    VLOG_DEBUG("kitchen", "__step_depends_on(step=%s)\n", step);

    list_foreach(dependencies, item) {
        struct oven_value_item* value = (struct oven_value_item*)item;
        if (strcmp(value->value, step) == 0) {
            // OK this step depends on the step we are resetting
            // so reset this step too
            return 1;
        }
    }
    return 0;
}

static int __reset_depending_steps(struct list* steps, const char* name)
{
    struct list_item* item;
    int               status;
    VLOG_DEBUG("kitchen", "__reset_depending_steps(name=%s)\n", name);

    list_foreach(steps, item) {
        struct recipe_step* recipeStep = (struct recipe_step*)item;

        // skip ourselves
        if (strcmp(recipeStep->name, name) != 0) {
            if (__step_depends_on(&recipeStep->depends, name)) {
                status = __reset_steps(steps, NULL, recipeStep->name);
                if (status) {
                    VLOG_ERROR("bake", "failed to reset step %s\n", recipeStep->name);
                    return status;
                }
            }
        }
    }
    return 0;
}

static int __reset_steps(struct list* steps, enum recipe_step_type stepType, const char* name)
{
    struct list_item* item;
    int               status;
    VLOG_DEBUG("kitchen", "__reset_steps(name=%s)\n", name);

    list_foreach(steps, item) {
        struct recipe_step* recipeStep = (struct recipe_step*)item;
        if ((recipeStep->type == stepType) ||
            (name && strcmp(recipeStep->name, name) == 0)) {
            // this should be deleted
            status = oven_clear_recipe_checkpoint(recipeStep->name);
            if (status) {
                VLOG_ERROR("bake", "failed to clear checkpoint %s\n", recipeStep->name);
                return status;
            }

            // clear dependencies
            status = __reset_depending_steps(steps, recipeStep->name);
        }
    }
    return 0;
}

int kitchen_prepare_recipe(struct kitchen* kitchen, struct recipe* recipe, enum recipe_step_type stepType)
{
    struct oven_recipe_options options;
    struct list_item*          item;
    int                        status;
    VLOG_DEBUG("kitchen", "kitchen_prepare_recipe()\n");

    if (stepType == RECIPE_STEP_TYPE_UNKNOWN) {
        return 0;
    }

    list_foreach(&recipe->parts, item) {
        struct recipe_part* part = (struct recipe_part*)item;

        __initialize_recipe_options(&options, part, recipe->environment.build.confinement, NULL);
        status = oven_recipe_start(&options);
        __destroy_recipe_options(&options);

        if (status) {
            return status;
        }

        status = __reset_steps(&part->steps, stepType, NULL);
        oven_recipe_end();

        if (status) {
            VLOG_ERROR("bake", "failed to build recipe %s\n", part->name);
            return status;
        }
    }
    return 0;
}

static void __initialize_generator_options(struct oven_generate_options* options, struct recipe_step* step)
{
    options->name           = step->name;
    options->profile        = NULL;
    options->system         = step->system;
    options->system_options = &step->options;
    options->arguments      = &step->arguments;
    options->environment    = &step->env_keypairs;
}

static void __initialize_build_options(struct oven_build_options* options, struct recipe_step* step)
{
    options->name           = step->name;
    options->profile        = NULL;
    options->system         = step->system;
    options->system_options = &step->options;
    options->arguments      = &step->arguments;
    options->environment    = &step->env_keypairs;
}

static void __initialize_script_options(struct oven_script_options* options, struct recipe_step* step)
{
    options->name   = step->name;
    options->script = step->script;
}

static int __make_recipe_steps(struct list* steps)
{
    struct list_item* item;
    int               status;
    VLOG_DEBUG("kitchen", "__make_recipe_steps()\n");
    
    list_foreach(steps, item) {
        struct recipe_step* step = (struct recipe_step*)item;
        printf("executing step '%s'\n", step->system);

        if (step->type == RECIPE_STEP_TYPE_GENERATE) {
            struct oven_generate_options genOptions;
            __initialize_generator_options(&genOptions, step);
            status = oven_configure(&genOptions);
            if (status) {
                VLOG_ERROR("bake", "failed to configure target: %s\n", step->system);
                return status;
            }
        } else if (step->type == RECIPE_STEP_TYPE_BUILD) {
            struct oven_build_options buildOptions;
            __initialize_build_options(&buildOptions, step);
            status = oven_build(&buildOptions);
            if (status) {
                VLOG_ERROR("bake", "failed to build target: %s\n", step->system);
                return status;
            }
        } else if (step->type == RECIPE_STEP_TYPE_SCRIPT) {
            struct oven_script_options scriptOptions;
            __initialize_script_options(&scriptOptions, step);
            status = oven_script(&scriptOptions);
            if (status) {
                VLOG_ERROR("bake", "failed to execute script\n");
                return status;
            }
        }
    }
    
    return 0;
}

static void __initialize_recipe_options(struct oven_recipe_options* options, struct recipe_part* part, int confined, struct list* ingredients)
{
    options->name          = part->name;
    options->relative_path = part->path;
    options->toolchain     = fridge_get_utensil_location(part->toolchain);
    options->ingredients   = ingredients;
    options->confined      = confined;
}

static void __destroy_recipe_options(struct oven_recipe_options* options)
{
    free((void*)options->toolchain);
}

int kitchen_make_recipe(struct kitchen* kitchen, struct recipe* recipe)
{
    struct oven_recipe_options options;
    struct list_item*          item;
    int                        status;
    struct list                ingredients;
    VLOG_DEBUG("kitchen", "kitchen_make_recipe()\n");

    // prepare the list of ingredients for the recipe parts
    list_init(&ingredients);

    list_foreach(&recipe->parts, item) {
        struct recipe_part* part = (struct recipe_part*)item;

        __initialize_recipe_options(&options, part, recipe->environment.build.confinement, &ingredients);
        status = oven_recipe_start(&options);
        __destroy_recipe_options(&options);

        if (status) {
            return status;
        }

        status = __make_recipe_steps(&part->steps);
        oven_recipe_end();

        if (status) {
            VLOG_ERROR("bake", "failed to build recipe %s\n", part->name);
            return status;
        }
    }

    return 0;
}

static void __initialize_pack_options(
    struct oven_pack_options* options, 
    struct recipe*            recipe,
    struct recipe_pack*       pack)
{
    memset(options, 0, sizeof(struct oven_pack_options));
    options->name             = pack->name;
    options->type             = pack->type;
    options->summary          = recipe->project.summary;
    options->description      = recipe->project.description;
    options->icon             = recipe->project.icon;
    options->version          = recipe->project.version;
    options->license          = recipe->project.license;
    options->eula             = recipe->project.eula;
    options->maintainer       = recipe->project.author;
    options->maintainer_email = recipe->project.email;
    options->homepage         = recipe->project.url;
    options->filters          = &pack->filters;
    options->commands         = &pack->commands;
    
    if (pack->type == CHEF_PACKAGE_TYPE_INGREDIENT) {
        options->bin_dirs = &pack->options.bin_dirs;
        options->inc_dirs = &pack->options.inc_dirs;
        options->lib_dirs = &pack->options.lib_dirs;
        options->compiler_flags = &pack->options.compiler_flags;
        options->linker_flags = &pack->options.linker_flags;
    }
}

int kitchen_make_packs(struct kitchen* kitchen, struct recipe* recipe)
{
    struct oven_pack_options packOptions;
    struct list_item*        item;
    int                      status;
    VLOG_DEBUG("kitchen", "kitchen_make_packs()\n");

    // include ingredients marked for packing
    list_foreach(&recipe->environment.runtime.ingredients, item) {
        struct recipe_ingredient* ingredient = (struct recipe_ingredient*)item;
        
        status = oven_include_filters(&ingredient->filters);
        if (status) {
            VLOG_ERROR("bake", "failed to include ingredient %s\n", ingredient->name);
            return status;
        }
    }

    list_foreach(&recipe->packs, item) {
        struct recipe_pack* pack = (struct recipe_pack*)item;

        __initialize_pack_options(&packOptions, recipe, pack);
        status = oven_pack(&packOptions);
        if (status) {
            VLOG_ERROR("bake", "failed to construct pack %s\n", pack->name);
            return status;
        }
    }
    return 0;
}
