/**
 * Copyright, Philip Meulengracht
 *
 * This program is free software : you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation ? , either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * 
 */

#include "private.h"
#include <errno.h>
#include <liboven.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/**
 * @brief Write a single-quoted shell literal.
 *
 * The generated config.site file is sourced by Autoconf, so values must be
 * quoted before they are written.
 */
static int __shell_literal(FILE* file, const char* value)
{
    if (file == NULL || value == NULL) {
        errno = EINVAL;
        return -1;
    }

    // The opening quote is required even when the value contains no spaces.
    if (fputc('\'', file) == EOF) {
        return -1;
    }

    // Escape each embedded quote because the complete value is shell-quoted.
    for (; *value != '\0'; value++) {
        // Replace a quote with the shell sequence that embeds it literally.
        if (*value == '\'') {
            // Stop if the escape sequence cannot be written completely.
            if (fputs("'\\''", file) == EOF) {
                return -1;
            }
        } else if (fputc(*value, file) == EOF) {
            return -1;
        }
    }

    return fputc('\'', file) == EOF ? -1 : 0;
}

/**
 * @brief Append ingredient include or library flags to a site assignment.
 */
static int __write_flags(FILE* file, const char* key, const char* option,
    const char* ingredients, const char* const* suffixes)
{
    // Start from the caller's existing flag value before appending ingredients.
    if (fprintf(file, "%s=\"${%s-}\"", key, key) < 0) {
        return -1;
    }

    // Emit one include or library flag for every supported ingredient suffix.
    for (size_t i = 0; suffixes[i] != NULL; i++) {
        char* path;
        int status;

        path = strpathcombine(ingredients, suffixes[i]);
        if (path == NULL) {
            return -1;
        }

        // Quote the shell assignment, not the flag value: configure expands
        // CPPFLAGS without reparsing embedded quote characters.
        status = fputs("' '", file) == EOF || __shell_literal(file, option) ||
            __shell_literal(file, path);
        free(path);

        // Abort because a partial site file would produce invalid flags.
        if (status != 0) {
            return -1;
        }
    }

    // Terminate the assignment so the next generated variable starts cleanly.
    return fputc('\n', file) == EOF ? -1 : 0;
}

/**
 * @brief Generate the Autoconf site file used for cross compilation.
 */
static int __write_site_file(const char* path, struct oven_backend_data* data)
{
    const char* includes[] = { "include", "usr/include", "usr/local/include", NULL };
    const char* libraries[] = { "lib", "usr/lib", "usr/local/lib", NULL };
    FILE* file;
    int status;

    if (path == NULL || data == NULL) {
        errno = EINVAL;
        return -1;
    }

    file = fopen(path, "w");
    if (file == NULL) {
        return -1;
    }

    // CPPFLAGS covers both C and C++; retain the recipe's existing compiler flags.
    status = fputs("# Generated by Chef for cross-compilation.\n", file) == EOF ||
        __write_flags(file, "CPPFLAGS", "-I", data->paths.build_ingredients, includes) ||
        __write_flags(file, "LDFLAGS", "-L", data->paths.build_ingredients, libraries);

    // Flush the complete generated site file before reporting success.
    if (fclose(file) != 0) {
        status = -1;
    }

    // Convert any failed write without errno into a useful I/O error.
    if (status != 0) {
        if (errno == 0) {
            errno = EIO;
        }
        return -1;
    }

    return 0;
}

/**
 * @brief Determine whether the requested target differs from the build host.
 */
static int __is_cross_compiling(struct oven_backend_data* data)
{
    const char* host = data->platform.host_platform != NULL
        ? data->platform.host_platform
        : CHEF_PLATFORM_STR;
    const char* arch = data->platform.host_architecture != NULL
        ? data->platform.host_architecture
        : CHEF_ARCHITECTURE_STR;

    return strcmp(data->platform.target_platform, host) != 0 ||
        (data->platform.target_architecture != NULL &&
            strcmp(data->platform.target_architecture, arch) != 0);
}

/**
 * @brief Check whether the recipe already supplied CONFIG_SITE.
 */
static int __custom_site(struct oven_backend_data* data)
{
    struct list_item* item;

    if (data->environment != NULL) {
        // Recipe environment entries override inherited CONFIG_SITE values.
        list_foreach(data->environment, item) {
            struct chef_keypair_item* pair = (struct chef_keypair_item*)item;

            if (strcmp(pair->key, "CONFIG_SITE") == 0) {
                return 1;
            }
        }
    }

    // Check inherited environment entries when the recipe supplied no override.
    for (size_t i = 0;
         data->process_environment != NULL && data->process_environment[i] != NULL;
         i++) {
        if (strncmp(data->process_environment[i], "CONFIG_SITE=", 12) == 0) {
            return 1;
        }
    }

    return 0;
}

/**
 * @brief Configure an Autotools project and optionally generate CONFIG_SITE.
 */
int configure_main(struct oven_backend_data* data, union chef_backend_options* options)
{
    struct backend_args args = { 0 };
    struct list overrides = { 0 };
    struct chef_keypair_item site = { 0 };
    char* configure = NULL;
    char* sitePath = NULL;
    int status = -1;

    // Reject incomplete paths before locating the configure script.
    if (backend_validate(data) != 0) {
        return -1;
    }

    configure = strpathcombine(data->paths.source, "configure");
    // Parse recipe options and rewrite prefixes before launching configure.
    if (configure == NULL || backend_args_parse(&args, data->arguments) != 0 ||
        backend_rewrite_prefix(&args, data->paths.install,
            backend_default_prefix(data->platform.target_platform, "/usr/local")) != 0) {
        goto cleanup;
    }

    // Generate CONFIG_SITE only for a cross build that lacks an explicit site.
    if (__is_cross_compiling(data) != 0 && __custom_site(data) == 0) {
        sitePath = strpathcombine(data->paths.build, "chef-config.site");
        // A missing or unwritable site file makes the cross setup incomplete.
        if (sitePath == NULL || __write_site_file(sitePath, data) != 0) {
            goto cleanup;
        }

        site.key = "CONFIG_SITE";
        site.value = sitePath;
        list_add(&overrides, &site.list_header);
    }

    status = backend_run(data, configure, &args,
        options != NULL && options->make.in_tree ? data->paths.source : data->paths.build,
        &overrides);

cleanup:
    free(sitePath);
    free(configure);
    backend_args_destroy(&args);
    return status;
}
