name: vchef
version: '1.4.3'
summary: The Vali Chef Package Management System
description: |
  Originally developed for the Vali/MollenOS operating system, this is a generic package management system that is 
  built as a lightweight alternative to current package managers. Its not only for package management, 
  but also as an application format. 

base: core22
grade: stable
confinement: strict
assumes: [snap-uid-envvars]

apps:
  bake:
    command: usr/bin/bake
  order:
    command: usr/bin/order
  serve:
    command: usr/bin/serve
  mkcdk:
    command: usr/bin/mkcdk
  served:
    command: usr/libexec/chef/served -vvv
    daemon: simple
    install-mode: disable
  waiterd:
    command: usr/libexec/chef/waiterd -vvv
    daemon: simple
    install-mode: disable
  cookd:
    command: usr/libexec/chef/cookd -vvv
    daemon: simple
    install-mode: disable
  cvd:
    command: usr/libexec/chef/cvd -vvv
    daemon: simple

parts:
  chef-src:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCHEF_BUILD_AS_SNAP=ON
    build-packages:
      - libfuse3-dev
      - libcap-dev
      - libcurl4-openssl-dev
      - libssl-dev
    stage-packages:
      - debootstrap
      - libfuse3-3
      - libcap2
      - libcurl4
      - libssl3
