name: vchef
version: '1.4.0'
summary: The Vali Chef Package Mangement System
description: |
  Originally developed for the Vali/MollenOS operating system, this is a generic package management system that is 
  built as a lightweight alternative to current package managers. Its not only for package management, 
  but also as an application format. 

base: core22
grade: stable
confinement: strict

apps:
  bake:
    command: usr/bin/bake
  order:
    command: usr/bin/order
  serve:
    command: usr/bin/serve
  served:
    command: usr/libexec/chef/served
    daemon: simple
    install-mode: disable
  waiterd:
    command: usr/libexec/chef/waiterd
    daemon: simple
    install-mode: disable
  cookd:
    command: usr/libexec/chef/cookd
    daemon: simple
    install-mode: disable

parts:
  chef-src:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCHEF_BUILD_AS_SNAP=ON
    build-packages:
      - libfuse3-dev
      - libcap-dev
      - execstack
    stage-packages:
      - debootstrap
      - libfuse3-3
      - libcap2
    override-build: |
      craftctl default
      execstack --clear-execstack $CRAFT_PART_INSTALL/usr/bin/mkvafs
      execstack --clear-execstack $CRAFT_PART_INSTALL/usr/bin/unmkvafs
